### PR TITLE
tui: restore full text when editing prompts with summarized content

### LINKED ISSUE #4015: Opening the editor essentially deletes pasted content
### Description

Hello!

I believe this issue existed before the v1 releases as well.
If after pasting content (and seeing `[Pasted ~11 lines]`), I open the editor - the content in the editor shows the summary (`[Pasted ~11 lines]`).

There are two separate issues here:
a. I don't have any option to expand or edit pasted content
b. If I edit something else in the editor and close it, the pasted content summary becomes plain text of "[Pasted ~11 lines]" and does not expand to the pasted lines when sending the prompt.

Same thing is happening with images, though of course, the handling should be different

I'm happy to try taking a crack at it.

### OpenCode version

v1.0.37

### Steps to reproduce

1. Paste enough content for a summary to occur / paste an image
2. Open editor with <leader>-e
3. Save an close the editor
4. Send the prompt
5. Note that the LLM didn't receive the text/image

### Screenshot and/or share link

Image

### Operating System

macOS 26.0.1

### Terminal

tmux in ghostty

### PR DESCRIPTION
**Pull request by maxandron**
Closes https://github.com/sst/opencode/issues/4015

Fixed the handling of pasted content and non-textual attachments.

New behaviour:
- Pasted textual content is expanded in the editor and remains expanded
- images / files pasted are preserved unless the virtual text is deleted in the editor

Small concerns:
1. To expand the text I used `.replace` on the virtual text. This assumes users will not type "[ Pasted 5 lines ]" in the prompt. A safer approach, perhaps, would be to do what the submit function does now and expand it based on the extmark locations. If going in this direction, we can consider extracting this into a helper function.
2. This also uses `.indexOf` to search for the virtual text of images/files. Which could slightly break if the user type "[ Image 1 ]". I don't see a simple solution for this at the time.

As both scenarios seem unlikely, I'm leaving this in to leave the change minimal and avoid further complicating the code.
But if you would prefer me to amend one to the safer approach - let me know.

### CODE REVIEW

**Comment by rekram1-node** [comment]
@maxandron amazing I will take a look at this today thank u

**Comment by maxandron** [comment]
my pleasure. let me know if I can help / improve

**Comment by rekram1-node** [comment]
whoops missed this one earlier Ill take a look now

File: packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx [hunk 1]
```diff
@@ -101,16 +101,81 @@ export function Prompt(props: PromptProps) {
...
+          const nonTextParts = store.prompt.parts.filter((p) => p.type !== "text")
+
+          const value = trigger === "prompt" ? "" : text
           const content = await Editor.open({ value, renderer })
-          if (content) {
-            input.setText(content, { history: false })
-            setStore("prompt", {
-              input: content,
-              parts: [],
+          if (!content) return
```
Comment (rekram1-node) [inline packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx:117]: Hm this doesn't quite work. 

If I type:

"hello", open editor -> save -> paste text, it jacks everything up

Oh I notice this is a bug in production too oof

Comment (rekram1-node) [reply packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx:117]: so ig nvm we need to address that one after

Comment (maxandron) [reply packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx:117]: Wow
Note that it doesn't happen at the point this branch was forked

(commit 9554abb56ef2998d13a31adc6ec85cd92cc71bf6)

So this was introduced by changes since

Thanks for reviewing
