### PR TITLE
fix: resolve homebrew upgrade requiring multiple runs (#5375)

### LINKED ISSUE #5375: `opencode upgrade` doesnt move to newest version
### Description

I tried upgrading opencode with the `opencode upgrade` command, the first time, it took me to a new version that was not the latest. I had to run it again before it went to the latest verison

### OpenCode version

1.0.138

### Steps to reproduce

_No response_

### Screenshot and/or share link

Image
Image

### Operating System

macOS

### Terminal

Ghostty

### PR DESCRIPTION
**Pull request by GeneCodeSavvy**
Fixes #5375 

The root cause was that for tap-installed formulas, version detection could fall back to a stale source and Homebrew’s auto-update behavior was being suppressed, so users wouldn’t always see the latest tap changes on the first run.

### What does this PR do?

- **Remove HOMEBREW_NO_AUTO_UPDATE:** Let brew auto-update taps before  
  upgrading (default behavior)

- **Fix version detection for tap formulas:** Use `brew info --json=v2`  
  for tap formulas instead of falling back to npm registry
  
### UPDATE:
  - Removing HOMEBREW_NO_AUTO_UPDATE updates all taps which is un-wanted.
  - Instead, we Manually `git pull` only the "anomalyco/tap" tap repo
  - Then run `brew upgrade` for the "anomalyco/tap/opencode"

### How did you verify your code works?
Running the command `bun run dev upgrade --print-logs`

### CODE REVIEW

File: packages/opencode/src/installation/index.ts [hunk 1]
```diff
@@ -148,10 +157,9 @@ export namespace Installation {
         break
       case "brew": {
         const formula = await getBrewFormula()
-        cmd = $`brew upgrade ${formula}`.env({
-          HOMEBREW_NO_AUTO_UPDATE: "1",
-          ...process.env,
-        })
+        // Don't set HOMEBREW_NO_AUTO_UPDATE - let brew auto-update taps before upgrading
```
Comment (rekram1-node) [inline packages/opencode/src/installation/index.ts]: I don't see why we'd need to do this? Im not a brew expert but why would we need to update other brew deps? I feel like HOMEBREW_NO_AUTO_UPDATE exists for the exact reason we are using it no?

Comment (GeneCodeSavvy) [reply packages/opencode/src/installation/index.ts]: ohh nice catch. Not a homebrew expert either. The command worked for me without the flag.

Making changes

**Comment by GeneCodeSavvy** [comment]
@rekram1-node After gpting this command would be the best workaround.  wdyt?

**Comment by rekram1-node** [comment]
> After gpting this command would be the best workaround. wdyt?

Not sure im following

**Comment by GeneCodeSavvy** [comment]
> > After gpting this command would be the best workaround. wdyt?
> 
> Not sure im following

What I’m proposing is: we just git pull our tap repo directly, then run brew upgrade on that formula. That way we only update anomalyco/tap and don’t touch homebrew-core or other taps.

**Comment by GeneCodeSavvy** [comment]
@rekram1-node, I have addressed the review comments. Thanks
