### PR TITLE
make compact interruptable

### LINKED ISSUE #2928: bug: /compact is not interruptable
seems like it was mentioned a while ago, but it does not work for me

https://github.com/sst/opencode/issues/606

https://github.com/user-attachments/assets/0a3580fc-3b67-49e2-b478-d4ca61cbfe01

### PR DESCRIPTION
**Pull request by rekram1-node**
fixes: #2928, #3256

### CODE REVIEW

File: packages/opencode/src/session/compaction.ts [hunk 1]
```diff
@@ -160,35 +173,90 @@ export namespace SessionCompaction {
...
-          summaryText += value.text
-          await Session.updatePart({
-            ...part,
-            text: summaryText,
-          })
+    try {
+      for await (const value of stream.fullStream) {
+        signal.throwIfAborted()
+        switch (value.type) {
+          case "start":
```
Comment (veracioux) [inline packages/opencode/src/session/compaction.ts]: You can combine them like this:
```
case "start":
case "text-start":
case "finish":
  continue
```

Comment (rekram1-node) [reply packages/opencode/src/session/compaction.ts]: yeah i still need to clean this up havrnt done that yet
