### PR TITLE
fix: escape ansi sequences

### LINKED ISSUE #1127: UI broke when agent was using a text editor.
Looks to me like the agent opened up a terminal text editor which then made the UI go super weird. 

Was using Claude 4 Sonnet.

Sorry for bad video but you can see what's going on. 

https://github.com/user-attachments/assets/0f75da7f-8399-4ce1-aa98-1dc78fb42514

### PR DESCRIPTION
**Pull request by rekram1-node**
Fixes: #1127

https://github.com/user-attachments/assets/9154415f-abea-4edf-b344-8fc9d4c975e6

### CODE REVIEW

File: packages/tui/internal/components/chat/message.go [hunk 1]
```diff
@@ -371,7 +371,8 @@ func renderToolDetails(
 			stdout := metadata["stdout"]
 			if stdout != nil {
 				command := toolInputMap["command"].(string)
-				body = fmt.Sprintf("```console\n> %s\n%s```", command, stdout)
+				out := util.StripAnsi(fmt.Sprintf("%s", stdout))
+				body = fmt.Sprintf("```console\n> %s\n%s```", command, out)
```
Comment (adamdotdevin) [inline packages/tui/internal/components/chat/message.go]: there's actually `ansi.Strip` usage elsewhere in the codebase, can you leverage the existing lib we use (charm/x/ansi i think)?

Comment (adamdotdevin) [reply packages/tui/internal/components/chat/message.go]: did you see this comment @rekram1-node ?

**Review by adamdotdevin — CHANGES_REQUESTED** [review]

**Comment by adamdotdevin** [comment]
sorry, forgot to submit the review!

File: packages/tui/internal/components/chat/message.go (hunk 1 above)
Comment (rekram1-node) [reply packages/tui/internal/components/chat/message.go]: Ah I should've tried to see if yall already had something, oopsie

Comment (adamdotdevin) [reply packages/tui/internal/components/chat/message.go]: no worries!

**Comment by rekram1-node** [comment]
Fixed
