### PR TITLE
fix(acp): preserve file attachment metadata during session replay

### LINKED ISSUE #9217: ACP session replay drops file attachment metadata and binary/text attachment handling
### Description

**Summary**  
When reloading an ACP session, file attachments are not replayed correctly, causing missing files, lost filenames, and incorrect rendering of text/binary content.

**Problem**  
During session replay:
- File parts in stored messages aren’t replayed to ACP clients.
- Images lose their original filenames (always shown as “image”).
- Binary files (PDFs, etc.) aren’t replayed.
- Text files appear as inline text instead of attachments.
- Synthetic text parts (LLM context) are incorrectly sent to ACP clients.

**Expected**  
Attachments should be replayed with preserved filenames and correct ACP content block types, and synthetic text should be filtered out.

**Actual**  
Attachments are missing or mis-typed, filenames are lost, and synthetic text is replayed.

**Steps to Reproduce**  
1. Start an ACP session and attach:
   - an image (e.g., `photo.png`),
   - a PDF (e.g., `doc.pdf`),
   - a text file (e.g., `notes.txt`).
2. End the session.
3. Reload the ACP session.
4. Observe replayed content in the ACP client.

**Proposed Solution**  
Update `processMessage()` in `packages/opencode/src/acp/agent.ts` to handle `file` parts during session replay:
- `file://` URLs → replay as `resource_link`
- `image/*` → replay as `image` blocks, preserving original filename
- `text/*` and `application/json` → replay as `resource` with decoded `text`
- binary files → replay as `resource` with `blob`

Also update `prompt()` to:
- Preserve filenames from `resource_link.name` and `image.uri`
- Handle `resource.blob` by storing file parts with data URLs
- Check `resource.text` truthiness (not just property existence)
- Filter `!part.synthetic` when replaying text

**Changes Outline**  
- Add file part handling in `processMessage()` for replay
- Filter synthetic text parts (`!part.synthetic`)
- Preserve filename from `resource_link.name` in prompt conversion
- Handle binary `resource.blob` in `prompt()`

### Plugins

_No response_

### OpenCode version

_No response_

### Steps to reproduce

1. Start an ACP session and attach:
- an image (e.g., photo.png),
- a PDF (e.g., doc.pdf),
- a text file (e.g., notes.txt).
2. End the session.
3. Reload the ACP session.
4. Observe replayed content in the ACP client.

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by liorshk**
## Problem

Fixes #9217 https://github.com/anomalyco/opencode/issues/9217

When reloading an ACP session, file attachments were not being replayed correctly:
- `file` type parts in stored messages were not being sent to ACP clients at all
- Images lost their original filenames (always showed as "image")
- Binary files (PDFs, etc.) were not replayed
- Text files appeared as inline text instead of as file attachments
- Synthetic text parts (injected for LLM context) were incorrectly sent to ACP clients

## Solution

Updated `processMessage()` in `agent.ts` to properly handle `file` parts during session replay:

- **`file://` URLs** → Replayed as `resource_link` blocks
- **Images** → Replayed as `image` blocks with preserved original filename
- **Text files** (`text/*`, `application/json`) → Replayed as `resource` blocks with decoded text
- **Binary files** → Replayed as `resource` blocks with blob data

Also updated the `prompt()` method to:
- Preserve original filenames from `resource_link.name` and `image.uri`
- Handle binary `resource` blocks (PDFs, etc.) by storing them as file parts with data URLs
- Check for truthy `resource.text` instead of just property existence

## Changes

- Add `file` part handling in `processMessage()` for session replay
- Filter synthetic text parts from ACP output (`!part.synthetic`)
- Preserve filename from `resource_link.name` when converting to internal parts
- Handle binary `resource.blob` blocks in `prompt()`

### CODE REVIEW

File: packages/opencode/src/session/message-v2.ts [hunk 1]
```diff
@@ -438,14 +438,37 @@ export namespace MessageV2 {
...
             })
-          // text/plain and directory files are converted into text parts, ignore them
-          if (part.type === "file" && part.mime !== "text/plain" && part.mime !== "application/x-directory")
-            userMessage.parts.push({
-              type: "file",
-              url: part.url,
-              mediaType: part.mime,
-              filename: part.filename,
-            })
+          if (part.type === "file") {
```
Comment (rekram1-node) [inline packages/opencode/src/session/message-v2.ts]: im skeptical of the updates here, what are the reasons here?

This file shouldnt really need updates to fix acp stuff

Comment (liorshk) [reply packages/opencode/src/session/message-v2.ts]: You're right - the message-v2.ts changes were unnecessary for this fix.
The initial approach tried to handle binary content detection at the LLM message conversion layer, but that was the wrong place to solve this problem. The actual issue is purely in the ACP layer: when replaying a session, OpenCode's file parts weren't being converted back to proper ACP content blocks (image, resource, resource_link).
The current fix keeps all changes in agent.ts.

I updated the PR and the PR description.
