### PR TITLE
Fix: Add --attach flag to opencode run (Fixes #3188)

### LINKED ISSUE #3188: opencode run --attach <server>
With the creation of `opencode serve` and `opencode attach` for connecting with TUI

It would be awesome to have `opencode run` attachable to a headless opencode server.

That would be great to reduce a lot the mcp servers cold boot time that happen at every `opencode run` to only the first query

Thanks to every people working on opencode, seeing a new release always light up my day

### PR DESCRIPTION
**Pull request by monke-yo**
# Add `--attach` flag to `opencode run`

Fixes #3188

## Changes

Added `--attach <url>` option to `opencode run` that connects to a running `opencode serve` instance via the SDK client, avoiding MCP server cold boot times on every invocation.

**Modified files:**
- run.ts - Added attach mode that uses `createOpencodeClient()` to connect to remote server instead of `bootstrap()`. Subscribes to SSE event stream and processes events identically to local mode.
- cli.mdx - Added `--attach` flag documentation with usage example.

**Usage:**
```bash
# Terminal 1
opencode serve

# Terminal 2
opencode run --attach http://localhost:4096 "Explain closures"
```

All existing flags (`--model`, `--agent`, `--file`, `--command`, `--continue`, `--session`, `--share`, `--format`, `--title`) work with `--attach`. Output format is identical to local execution.

### CODE REVIEW

**Comment by rekram1-node** [comment]
I think ideally we wouldn't need to duplicate so much logic

**Comment by monke-yo** [comment]
@rekram1-node reused some logic, check again

File: packages/opencode/src/cli/cmd/run.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ import { SessionPrompt } from "../../session/prompt"
 import { EOL } from "os"
 import { Permission } from "@/permission"
 import { select } from "@clack/prompts"
+import { createOpencodeClient, type OpencodeClient } from "@opencode-ai/sdk"
```
Comment (rekram1-node) [inline packages/opencode/src/cli/cmd/run.ts:10]: There are quite a few unused imports now can we remove them?

File: packages/opencode/src/cli/cmd/run.ts [hunk 2]
```diff
@@ -124,216 +130,228 @@ export const RunCommand = cmd({
...
-          if (outputJsonEvent("step_start", { part })) return
-        }
+      return await execute(sdk, sessionID)
+    }
 
-        if (part.type === "step-finish") {
-          if (outputJsonEvent("step_finish", { part })) return
-        }
+    await bootstrap(process.cwd(), async () => {
+      const server = Server.listen({ port: 0, hostname: "127.0.0.1" })
```
Comment (rekram1-node) [inline packages/opencode/src/cli/cmd/run.ts]: should there be a port arg too maybe?

Comment (monke-yo) [reply packages/opencode/src/cli/cmd/run.ts]: makes sense, will do that
