### PR TITLE
fix(bedrock): use reasoningConfig for Anthropic models on Bedrock

### LINKED ISSUE #7357: AWS Bedrock Claude extended thinking uses wrong API format (reasoningConfig instead of thinking.budget_tokens)
## Summary

OpenCode's AWS Bedrock provider sends `reasoningConfig.maxReasoningEffort` for extended thinking, but AWS Bedrock Claude models require `thinking.budget_tokens`. This causes the Ctrl+T thinking toggle and `--variant` flag to have no effect.

## Problem

When using AWS Bedrock Claude models (e.g., `amazon-bedrock/anthropic.claude-opus-4-5-20251101-v1:0`), toggling thinking with Ctrl+T between low/medium/high does nothing because the wrong API format is sent.

### What OpenCode sends:
```json
{
  "reasoningConfig": {
    "type": "enabled",
    "maxReasoningEffort": "low" | "medium" | "high"
  }
}
```

### What AWS Bedrock actually requires:
```json
{
  "thinking": {
    "type": "enabled",
    "budget_tokens": 10000
  }
}
```

## Confirmed via Testing

Tested with CLI:
```bash
opencode run "What is 27 * 453?" --model "amazon-bedrock/anthropic.claude-opus-4-5-20251101-v1:0" --variant "high" --format json
```

Output shows `"reasoning":0` - no reasoning tokens used:
```json
{"type":"step_finish",...,"tokens":{"input":332,"output":16,"reasoning":0,...}}
```

**Config workaround also doesn't work** because the provider transform overrides it:
```json
{
  "provider": {
    "amazon-bedrock": {
      "models": {
        "anthropic.claude-opus-4-5-20251101-v1:0": {
          "options": {
            "thinking": {
              "type": "enabled",
              "budgetTokens": 32000
            }
          }
        }
      }
    }
  }
}
```

## Root Cause

In `packages/opencode/src/provider/transform.ts`, the `variants` function for `@ai-sdk/amazon-bedrock` returns:

```typescript
reasoningConfig: {
  type: "enabled",
  maxReasoningEffort: effort,  // "low", "medium", "high"
}
```

But AWS Bedrock's Messages API for Claude extended thinking requires the `thinking` object with `budget_tokens` (a number), not `maxReasoningEffort` (a string).

## AWS Documentation Reference

From [AWS Bedrock Extended Thinking Docs](https://docs.aws.amazon.com/bedrock/latest/userguide/claude-messages-extended-thinking.html):

> To turn on extended thinking, add a `thinking` object, with the `thinking` parameter set to enabled and the `budget_tokens` set to a specified token budget for extended thinking.

Supported models:
- `anthropic.claude-opus-4-5-20251101-v1:0`
- `anthropic.claude-sonnet-4-5-20250929-v1:0`
- `anthropic.claude-haiku-4-5-20251001-v1:0`
- `anthropic.claude-opus-4-20250514-v1:0`
- `anthropic.claude-sonnet-4-20250514-v1:0`
- `anthropic.claude-3-7-sonnet-20250219-v1:0`

## Proposed Fix

Update the `variants` function for `@ai-sdk/amazon-bedrock` to use the same format as Anthropic direct:

```typescript
// For amazon-bedrock, use thinking.budgetTokens like Anthropic
case "@ai-sdk/amazon-bedrock":
  return {
    low: {
      thinking: { type: "enabled", budgetTokens: 10000 }
    },
    medium: {
      thinking: { type: "enabled", budgetTokens: 32000 }
    },
    high: {
      thinking: { type: "enabled", budgetTokens: 80000 }
    },
    max: {
      thinking: { type: "enabled", budgetTokens: 128000 }
    }
  }
```

## Environment

- Model: `amazon-bedrock/anthropic.claude-opus-4-5-20251101-v1:0`
- OpenCode version: latest
- AWS Region: (varies)

## Impact

- **Ctrl+T toggle**: Does nothing for Bedrock models
- **--variant flag**: Does nothing for Bedrock models  
- **Config workaround**: Overridden by provider transform
- **Result**: Extended thinking is completely broken for all AWS Bedrock Claude models

### PR DESCRIPTION
**Pull request by Adam8234**
### What does this PR do?

Added Regex Check for anthropic models to add reasoning for variants.

Bedrocks Model id's can be set as:
- Global (For Global Inference) `global.` prefix
- US (Cross Region) `us.` prefix.
- Region based (No prefix)

### How did you verify your code works?

Tested locally with bun run dev with Bedrock Provider with variants set:
- Before Change - no thinking tokens
- After change - thinking tokens

Fixes #7357

### CODE REVIEW

File: packages/opencode/src/provider/transform.ts [hunk 1]
```diff
@@ -364,6 +364,25 @@ export namespace ProviderTransform {
 
       case "@ai-sdk/amazon-bedrock":
         // https://v5.ai-sdk.dev/providers/ai-sdk-providers/amazon-bedrock
+        // For Anthropic models on Bedrock, use reasoningConfig with budgetTokens
+        if (/^(us\.|global\.)?anthropic\./.test(model.api.id)) {
```
Comment (rekram1-node) [inline packages/opencode/src/provider/transform.ts]: why the us or global prefix? Cant u just do a if anthropic in id?

**Comment by rekram1-node** [comment]
just 1 question

File: packages/opencode/src/provider/transform.ts (hunk 1 above)
Comment (Adam8234) [reply packages/opencode/src/provider/transform.ts]: That would work, but wanted more robust solution. If you want I can switch it to just check for anthropic in the name.

Edit: I'll update, simpler to just check for anthropic in the name.
