### PR TITLE
fix: lsp bug

### LINKED ISSUE #1985: lsp: clangd: disabled: true in the config doesn't disable clangd
I have the following config, and clangd is still used by opencode.
```
{
  "$schema": "https://opencode.ai/config.json",
  "snapshot": false,
  "lsp": {
    "clangd": {
      "disabled": true
    }
  },
}
```

### PR DESCRIPTION
**Pull request by rekram1-node**
fixes: #1985

- Added extra logs
- fixed bad lsp reference

### CODE REVIEW

File: packages/opencode/src/lsp/index.ts [hunk 1]
```diff
@@ -57,11 +57,15 @@ export namespace LSP {
     "lsp",
     async () => {
       const clients: LSPClient.Info[] = []
-      const servers: Record<string, LSPServer.Info> = LSPServer
```
Comment (rekram1-node) [inline packages/opencode/src/lsp/index.ts:60]: this was the primary culprit, it also behaves counter to the documentation: https://opencode.ai/docs/lsp/#disabling-lsp-servers

Instead of the server being "typescript" it was titled "Typescript" as per the export, figured it would be better to change to server ids instead for consitency w/ docs

File: packages/opencode/src/lsp/index.ts [hunk 2]
```diff
@@ -104,7 +115,7 @@ export namespace LSP {
     const s = await state()
     const extension = path.parse(file).ext
     const result: LSPClient.Info[] = []
-    for (const server of Object.values(LSPServer)) {
+    for (const server of Object.values(s.servers)) {
```
Comment (rekram1-node) [inline packages/opencode/src/lsp/index.ts:118]: figured only enabled servers should have clients
