### PR TITLE
fix: Explicitly exit CLI to prevent hanging subprocesses

### LINKED ISSUE #854: On exit - hangs in terminal
Image

If start opencode and exit - all is ok
But if run any requests, and exit - it hangs.

### LINKED ISSUE #1001: Again hangs after quit
Image

### LINKED ISSUE #1195: Some docker based MCPs prevent opencode shutdown
Take this opencode.json configuration as an example: 

```
{
        "$schema": "https://opencode.ai/config.json",
        "autoupdate": true,
        "share": "disabled",
        "instructions": [
                ".opencode.instructions.md"
        ],
        "mcp": {
                "clickhouse": {
                        "type": "local",
                        "command": [
                                "docker",
                                "run",
                                "--net", "host",
                                "-i",
                                "--rm",
                                "-e", "CLICKHOUSE_HOST",
                                "-e", "CLICKHOUSE_PORT",
                                "-e", "CLICKHOUSE_USER",
                                "-e", "CLICKHOUSE_SECURE",
                                "-e", "CLICKHOUSE_VERIFY",
                                "-e", "CLICKHOUSE_CONNECT_TIMEOUT",
                                "-e", "CLICKHOUSE_SEND_RECEIVE_TIMEOUT",
                                "-e", "CLICKHOUSE_PASSWORD",
                                "mcp/clickhouse"
                        ],
                        "environment": {
                                "CLICKHOUSE_HOST": "localhost",
                                "CLICKHOUSE_PORT": "8123",
                                "CLICKHOUSE_USER": "chuser",
                                "CLICKHOUSE_SECURE": "false",
                                "CLICKHOUSE_VERIFY": "false",
                                "CLICKHOUSE_CONNECT_TIMEOUT": "30",
                                "CLICKHOUSE_SEND_RECEIVE_TIMEOUT": "30",
                                "CLICKHOUSE_PASSWORD": "chpassword"
                        }
                }
        }
}
```

Once the session is initiated and the docker container starts, it will prevent the normal shutdown of opencode. When I manually execute`docker rm -f $CONTAINER`, then opencode correctly stops.

And interestingly enough (probably because it correctly traps SIGINT), if I call `/exit` and then ˆC it out, the docker container is also correctly stopped.

More info: 
```
$ opencode --version
0.3.48
$ uname -a
Darwin MBP.local 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:52:00 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6031 arm64
```

### LINKED ISSUE #1431: opencode hangs when trying to end it
this is related to MCPs, without having any MCPs configured, this does not happen.

in my case it´s:

```json
"mcp": {
    "jetbrains": {
      "type": "local",
      "command": ["npx","-y","@jetbrains/mcp-proxy"],
      "enabled": true,
      "environment": {
        "IDE_PORT": "63341",
        "HOST": "192.168.178.xxx"
      }
    }
```

when killing all node procsses:

`kill -9 $(ps ax|grep node|grep jetbrains|awk {'print $1'})`

opencode ends......

this - i guess - is related to #1001 #1244

### LINKED ISSUE #1717: TUI exits but process hangs (no shell return) when opencode.json is present
## Summary: 

Exiting the TUI closes the UI but the opencode process doesn’t return control to the shell.  
I have to Ctrl+C to regain the prompt.

This does not occur if I remove my opencode.json, but it consistently reproduces when I restore it.

## Steps to reproduce

1. Use opencode with the config below.
2. Open the TUI, then /exit
3. Observe that the terminal does not return to the shell; process appears suspended until Ctrl+C.

## Behaviour
- Expected behavior: After exiting the TUI, opencode should terminate and return control to the shell.
 - Actual behavior: TUI closes, but the opencode command hangs and requires Ctrl+C.
 - Workaround: Remove opencode.json (issue no longer reproduces).

## Environment
 - OS: Darwin Varuns-MacBook-Pro.local 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:48:46 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T8103 arm64
 - Shell: zsh 5.9
 - sst-opencode version: 0.4.1
 - Install method: YOLO (Curl + Bash)
 - Additional context
    - The issue seems tied to the config below.  
Notably, MCP providers are launched via docker run -i which may be keeping stdin open after the TUI exits.

Config:
```json
{
  "$schema": "https://opencode.ai/config.json",
  "share": "disabled",
  "permission": {
    "bash": {
      "git commit": "ask",
      "git status*": "allow",
      "git log*": "allow",
      "git diff*": "allow",
      "git push": "deny",
      "git reset": "ask",
      "git rebase": "ask",
      "git merge": "ask",
      "git cherry-pick": "ask",
      "sudo": "ask",
      "rm": "ask",
      "mv": "ask",
      "chmod": "ask",
      "chown": "ask"
    }
  },
  "mcp": {
    "memory": {
      "type": "local",
      "command": [
        "docker",
        "run",
        "-i",
        "-v",
        "claude-memory:/app/dist",
        "--rm",
        "mcp/memory"
      ],
      "enabled": true
    },
    "sequentialthinking": {
      "type": "local",
      "command": [
        "docker",
        "run",
        "--rm",
        "-i",
        "mcp/sequentialthinking"
      ],
      "enabled": true
    }
  },
  "provider": {
    "openai": {
      "models": {
        "gpt-5": {
          "name": "OpenAI GPT-5 (high reasoning)",
          "options": {
            "reasoningEffort": "high"
          }
        },
        "o3": {
          "name": "OpenAI o3 (high reasoning)",
          "options": {
            "reasoningEffort": "high"
          }
        }
      }
    }
  }
}
```

### LINKED ISSUE #1810: /exit hangs after new session
Appears /exit hangs after new session is created. Exiting opencode after loading an existing session works fine as does exiting without creating a new session.

### PR DESCRIPTION
**Pull request by veracioux**
Reproduced using MCP config from: https://github.com/sst/opencode/issues/1717

The easiest way to reproduce (and verify the fix) is to run `opencode run hi`.

Investigation:
- The MCP servers from the issue are run via `docker run`
- When opencode exits, the `ai` library sends SIGTERM to all child MCP processes that use stdio transports
- The problem is that the child processes are the `docker run` client, and `SIGTERM` isn't properly delivered, unless `docker run --init` was used. So the subprocesses stick around, preventing opencode from exiting. I verified this with a minimalistic subprocess-spawning bun program and `strace`
- What does work though, is killing the opencode process itself using `process.exit`, in which case `SIGTERM` is delivered correctly
- Fix: I added a `process.exit()` when the CLI is done with everything.

NOTE: Issue also happens in (some, maybe all) MCP servers wrapped by shell scripts, which this also fixes.

---

Edit:
I also found some places that don't properly await Promises and are liable to cause hangs before process exit. I changed those. I also replaced some `for () { await ... }` with `await Promise.all(...)` to potentially speed up cleanups of unrelated resources (which hence can be performed concurrently).

Improved INFO logs for ensureTitle - it's now awaited and logged so it can be more obvious from `--print-logs` that that is the reason why OC hangs before exiting.

---

Closes #854.
Closes #1001.
Closes #1195.
Closes #1431.
Closes #1717.
Closes #1810.

Might fix:
- #2406.
- #3213

Possibly related, but I'm not very confident this is fixed by the PR:
- #2819

### CODE REVIEW

**Comment by veracioux** [comment]
Rebased to remove unintended extra commit.

File: packages/opencode/src/session/prompt.ts [hunk 1]
```diff
@@ -335,6 +336,9 @@ export namespace SessionPrompt {
       }
       state().queued.delete(input.sessionID)
       SessionCompaction.prune(input)
+      log.info("waiting for session title to be generated")
+      await ensureTitlePromise
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: are you sure we wanna await here, doesnt that make title generation blocking

Comment (veracioux) [reply packages/opencode/src/session/prompt.ts]: Yes, definitely. The promise will be running either way, and if we don't await it here, it will hang around until either it resolves or the process exits.

I think it makes sense to await it here, as it is the end of the LLM's response to the user's input, meaning it can run concurrently with the LLM's response.

Also, since I do `process.exit()` at the end of `index.ts` to work around those dockerized MCP servers, if I don't await this here, the `process.exit()` will be reached before the ensureTitlePromise resolves, so it will be interrupted and the title won't be saved.

Comment (veracioux) [reply packages/opencode/src/session/prompt.ts]: @rekram1-node Tweaked slightly to address your concern. See https://github.com/sst/opencode/pull/3083/commits/1e0846fb63fb25c09f7b1839fb7a360b2a755ec6.

File: packages/opencode/src/index.ts [hunk 2]
```diff
@@ -129,6 +127,10 @@ try {
   if (formatted) UI.error(formatted)
   if (formatted === undefined) UI.error("Unexpected error, check log file at " + Log.file() + " for more details")
   process.exitCode = 1
+} finally {
+  // Some subprocesses don't react properly to SIGTERM and similar signals.
+  // Most notably, some docker-container-based MCP servers don't handle such signals unless
+  // run using `docker run --init`.
+  // Explicitly exit to avoid any hanging subprocesses.
+  process.exit();
```
Comment (rekram1-node) [inline packages/opencode/src/index.ts:141]: are there any other cases besides the docker mcps?

Can't we just track the pid from transports and send a SIGKILL if they are still running post close?

File: packages/opencode/src/session/prompt.ts [hunk 3]
```diff
@@ -76,10 +76,14 @@ export namespace SessionPrompt {
 
       return {
         queued,
+        ensureTitlePromise: undefined as Promise<void> | undefined,
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: what if I have multiple calls to prompt at once?

Comment (rekram1-node) [reply packages/opencode/src/session/prompt.ts]: Keep in mind that opencode server isn't tied just to the normal server + tui, it can also have other use cases ex:

https://github.com/sst/opencode/blob/dev/packages/sdk/js/example/example.ts

File: packages/opencode/src/index.ts (hunk 2 above)
Comment (veracioux) [reply packages/opencode/src/index.ts:141]: I have a shell script wrapping an stdio MCP that has the same behavior. I can send it to you later today. I can imagine there can be other cases where an MCP misbehaves in a similar way. I have seen a few MCP server implementations and the general vibe is not high quality or well thought out.

I would like to avoid using SIGKILL. Fact of the matter is, the actual MCP server process receives SIGTERM when process.exit() is called. I confirmed that by running `strace` on the container's PID. But from the POV of OC, the child process is not the MCP server, but rather the docker client managing the MCP server.

The PID from the transports is an implementation detail - I would like to avoid using that too.

Any subprocess not under our control can cause the hang. The process.exit is a panacea, and as long as we do proper awaits, it won't cause any issues. Which we do for the most part.

File: packages/opencode/src/session/prompt.ts (hunk 3 above)
Comment (veracioux) [reply packages/opencode/src/session/prompt.ts]: Ah yes, I'll make some tweaks. Thanks for pointing out.

Comment (veracioux) [reply packages/opencode/src/session/prompt.ts]: See newest commits. They should address both these concerns.

File: packages/opencode/src/index.ts (hunk 2 above)
Comment (veracioux) [reply packages/opencode/src/index.ts:141]: The shell script + how I use it in `opencode.json`, as promised: https://gist.github.com/veracioux/3a9fe2ea06fca0d16852481030d9297e

File: packages/opencode/src/file/watcher.ts [hunk 4]
```diff
@@ -63,7 +63,8 @@ export namespace FileWatcher {
       return { sub }
     },
     async (state) => {
-      state.sub?.unsubscribe()
+      if (!state.sub) return
+      Instance.trackPromises([state.sub.unsubscribe()])
```
Comment (rekram1-node) [inline packages/opencode/src/file/watcher.ts]: why do we need to trackPromises it if this is already in the dispose function? Cant we just await it?
