### PR TITLE
fix: transform MCP tool schemas for Google/Gemini compatibility

### LINKED ISSUE #4512: sanitize tools for Gemini 3 compatibility
### Description

Got error when try to send message to gemini 3 model: 

Invalid value at 'tools.function_declarations[12].parameters.properties[0].value.enum[0]' (TYPE_STRING), 0
Invalid value at 'tools.function_declarations[12].parameters.properties[0].value.enum[1]' (TYPE_STRING), 1
Invalid value at 'tools.function_declarations[12].parameters.properties[0].value.enum[2]' (TYPE_STRING), 2
Invalid value at 'tools.function_declarations[12].parameters.properties[1].value.enum[0]' (TYPE_STRING), 0
Invalid value at 'tools.function_declarations[12].parameters.properties[1].value.enum[1]' (TYPE_STRING), 1
Invalid value at 'tools.function_declarations[12].parameters.properties[1].value.enum[2]' (TYPE_STRING), 2
Invalid value at 'tools.function_declarations[12].parameters.properties[1].value.enum[3]' (TYPE_STRING), 3

After research i found out that problem was caused by Ponter MCP, would you handle properties type ?

### OpenCode version

v1.0.78

### Steps to reproduce

1) Add MCP: 
"pointer": {
      "type": "local",
      "command": ["npx", "-y", "@mcp-pointer/server@latest", "start"],
      "environment": {
      "MCP_POINTER_PORT": "7007"
}

2) Try to send message

### Screenshot and/or share link

_No response_

### Operating System

Nobara 42

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by ZGltYQ**
- Apply ProviderTransform.schema() to MCP tools to convert integer enums to strings
  - Convert function declaration to arrow function for strict mode compliance
  - Fix variable shadowing in content iteration loop

  Resolves 'Invalid value at tools.function_declarations' error when using
  Google/Gemini with MCP tools that have integer enum parameters.

Closes:  #4512

### CODE REVIEW

**Comment by rekram1-node** [comment]
We need this but I tested with several providers and this does not work correctly. Your changes will basically delete the input schema entirely 

I'd recommend not using type error silencing because it is going to make code harder to maintain.

File: packages/opencode/src/session/prompt.ts [hunk 1]
```diff
@@ -728,64 +728,77 @@ export namespace SessionPrompt {
...
-            callID: opts.toolCallId,
-          },
-          result,
-        )
+      // Transform the schema for provider compatibility (e.g., convert integer enums to string enums for Google)
+      const transformedSchema = ProviderTransform.schema(
+        input.model.providerID,
+        input.model.modelID,
+        // @ts-expect-error - accessing internal schema property
+        item.inputSchema ?? item.parameters ?? {},
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: This is the issue right here

**Comment by ZGltYQ** [comment]
Fixed. I have tested it with grok, anthropic, gemini etc.

**Comment by rekram1-node** [comment]
This looks good ill test more tmr just to be sure.

We used to sanitize the tools way better before we did the zodv4 migration and then we kinda just forgot about it ig:
```
function sanitizeGeminiParameters(schema: z.ZodTypeAny, visited = new Set()): z.ZodTypeAny {
    if (!schema || visited.has(schema)) {
      return schema
    }
    visited.add(schema)

    if (schema instanceof z.ZodDefault) {
      const innerSchema = schema.removeDefault()
      // Handle Gemini's incompatibility with `default` on `anyOf` (unions).
      if (innerSchema instanceof z.ZodUnion) {
        // The schema was `z.union(...).default(...)`, which is not allowed.
        // We strip the default and return the sanitized union.
        return sanitizeGeminiParameters(innerSchema, visited)
      }
      // Otherwise, the default is on a regular type, which is allowed.
      // We recurse on the inner type and then re-apply the default.
      return sanitizeGeminiParameters(innerSchema, visited).default(schema._def.defaultValue())
    }

    if (schema instanceof z.ZodOptional) {
      return z.optional(sanitizeGeminiParameters(schema.unwrap(), visited))
    }

    if (schema instanceof z.ZodObject) {
      const newShape: Record<string, z.ZodTypeAny> = {}
      for (const [key, value] of Object.entries(schema.shape)) {
        newShape[key] = sanitizeGeminiParameters(value as z.ZodTypeAny, visited)
      }
      return z.object(newShape)
    }

    if (schema instanceof z.ZodArray) {
      return z.array(sanitizeGeminiParameters(schema.element, visited))
    }

    if (schema instanceof z.ZodUnion) {
      // This schema corresponds to `anyOf` in JSON Schema.
      // We recursively sanitize each option in the union.
      const sanitizedOptions = schema.options.map((option: z.ZodTypeAny) => sanitizeGeminiParameters(option, visited))
      return z.union(sanitizedOptions as [z.ZodTypeAny, z.ZodTypeAny, ...z.ZodTypeAny[]])
    }

    if (schema instanceof z.ZodString) {
      const newSchema = z.string({ description: schema.description })
      const safeChecks = ["min", "max", "length", "regex", "startsWith", "endsWith", "includes", "trim"]
      // rome-ignore lint/suspicious/noExplicitAny: <explanation>
      ;(newSchema._def as any).checks = (schema._def as z.ZodStringDef).checks.filter((check) =>
        safeChecks.includes(check.kind),
      )
      return newSchema
    }

    return schema
  }

  function optionalToNullable(schema: z.ZodTypeAny): z.ZodTypeAny {
    if (schema instanceof z.ZodObject) {
      const shape = schema.shape
      const newShape: Record<string, z.ZodTypeAny> = {}

      for (const [key, value] of Object.entries(shape)) {
        const zodValue = value as z.ZodTypeAny
        if (zodValue instanceof z.ZodOptional) {
          newShape[key] = zodValue.unwrap().nullable()
        } else {
          newShape[key] = optionalToNullable(zodValue)
        }
      }

      return z.object(newShape)
    }

    if (schema instanceof z.ZodArray) {
      return z.array(optionalToNullable(schema.element))
    }

    if (schema instanceof z.ZodUnion) {
      return z.union(
        schema.options.map((option: z.ZodTypeAny) => optionalToNullable(option)) as [
          z.ZodTypeAny,
          z.ZodTypeAny,
          ...z.ZodTypeAny[],
        ],
      )
    }

    return schema
  }
  ```
