### PR TITLE
fix: encode non-ASCII directory paths in v1 SDK HTTP headers

### LINKED ISSUE #13023: Windows: opencode fails in non-ASCII (Chinese) directory with invalid x-opencode-directory header
Environment: opencode 1.1.55 on Windows (PowerShell), locale zh-CN, working directory C:\Users\baode\OneDrive\桌面. Repro steps: (1) cd C:\Users\baode\OneDrive\桌面 (2) run opencode. Actual result: startup fails with TypeError: Header 'x-opencode-directory' has invalid value containing Chinese path characters. Expected result: opencode should start normally in Unicode/non-ASCII paths. Workaround: running from ASCII-only path works (for example C:\work\test).

### PR DESCRIPTION
**Pull request by MrMushrooooom**
### What does this PR do?

Fixes #13023

#11344 added `directory: Instance.directory` to the plugin client, but the v1 SDK (`packages/sdk/js/src/client.ts`) sends the raw path as the `x-opencode-directory` header. 

`Headers.set()` rejects non-ASCII characters per the Fetch standard, so any project path with Chinese/Japanese/Korean characters throws a TypeError, breaking all project functionality.

This applies the same `encodeURIComponent` fix already in the v2 SDK (#7145) to the v1 SDK.

### How did you verify your code works?

Reproduced the bug by running `opencode ~/path/测试中文路径` — got `TypeError: Header 'x-opencode-directory' has invalid value`. After the fix, `bun run dev ~/path/测试中文路径` starts normally with no errors.

### CODE REVIEW

File: packages/sdk/js/src/client.ts [hunk 1]
```diff
@@ -19,9 +19,11 @@ export function createOpencodeClient(config?: Config & { directory?: string }) {
   }
 
   if (config?.directory) {
+    const isNonASCII = /[^\x00-\x7F]/.test(config.directory)
+    const encodedDirectory = isNonASCII ? encodeURIComponent(config.directory) : config.directory
```
Comment (adamdotdevin) [inline packages/sdk/js/src/client.ts]: Can we just always encode? Any need to conditionally do so?

Comment (MrMushrooooom) [reply packages/sdk/js/src/client.ts]: Good point...will simplify to always encode.
