### PR TITLE
fix(tui): worker path resolution in dev mode

### LINKED ISSUE #3777: bun dev with different project dir fails
### Description

After updating to the latest "dev" branch (which I think is opentui now) - commit 10523c43723a6c6d1f352d707a1b389317733af3

Previous versions allowed:

```
bun install
bun dev ../path/to/my/project
```

But now I get:

```
% bun dev ../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../path/to/my/project
Error: Failed to change directory to /Users/cjs/repos/opencode/packages/path/to/my/project
```

If I try to add more ../ I get:

```
% bun dev ../../../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../../../path/to/my/project
ErrorEvent {
  type: "error",
  message: "BuildMessage: ModuleNotFound resolving \"./src/cli/cmd/tui/worker.ts\" (entry point)",
  error: null,
}
```

How can I run it in dev mode with a separate path now?

### PR DESCRIPTION
**Pull request by paralin**
Previous versions allowed:

```
bun install
bun dev ../path/to/my/project
```

But now I get:

```
% bun dev ../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../path/to/my/project
Error: Failed to change directory to /Users/cjs/repos/opencode/packages/path/to/my/project
```

If I try to add more ../ I get:

```
% bun dev ../../../path/to/my/project
$ bun run --cwd packages/opencode --conditions=browser src/index.ts ../../../path/to/my/project
ErrorEvent {
  type: "error",
  message: "BuildMessage: ModuleNotFound resolving \"./src/cli/cmd/tui/worker.ts\" (entry point)",
  error: null,
}
```

This commit fixes this by using relative path resolution.

Fixes: #3777

### CODE REVIEW

File: packages/opencode/src/cli/cmd/tui/thread.ts [hunk 1]
```diff
@@ -52,7 +52,11 @@ export const TuiThreadCommand = cmd({
         default: "127.0.0.1",
       }),
   handler: async (args) => {
-    const cwd = args.project ? path.resolve(args.project) : process.cwd()
+    // Resolve relative paths against PWD to preserve behavior when using --cwd flag
+    const baseCwd = process.env.PWD ?? process.cwd()
+    const cwd = args.project ? path.resolve(baseCwd, args.project) : process.cwd()
+    const workerPath = new URL("./worker.ts", import.meta.url).href
```
Comment (kommander) [inline packages/opencode/src/cli/cmd/tui/thread.ts]: All the other changes make sense. Need to make sure this is still picked up by `bun --compile` to bundle the worker into the standalone executable. Can you try running the build script in the opencode package, move the executable to a dir far away and see if it still works?

**Comment by kommander** [comment]
This works as compiled standalone executable and for dev:

```diff
diff --git a/packages/opencode/script/build.ts b/packages/opencode/script/build.ts
index 1d3a3fac..4ce8bfba 100755
--- a/packages/opencode/script/build.ts
+++ b/packages/opencode/script/build.ts
@@ -41,7 +41,9 @@ for (const [os, arch] of targets) {
 
   const opentui = `@opentui/core-${os === "windows" ? "win32" : os}-${arch.replace("-baseline", "")}`
   await $`mkdir -p ../../node_modules/${opentui}`
-  await $`npm pack ${opentui}@${pkg.dependencies["@opentui/core"]}`.cwd(path.join(dir, "../../node_modules"))
+  await $`npm pack ${opentui}@${pkg.dependencies["@opentui/core"]}`.cwd(
+    path.join(dir, "../../node_modules"),
+  )
   await $`tar -xf ../../node_modules/${opentui.replace("@opentui/", "opentui-")}-*.tgz -C ../../node_modules/${opentui} --strip-components=1`
 
   const watcher = `@parcel/watcher-${os === "windows" ? "win32" : os}-${arch.replace("-baseline", "")}${os === "linux" ? "-glibc" : ""}`
@@ -49,7 +51,11 @@ for (const [os, arch] of targets) {
   await $`npm pack ${watcher}`.cwd(path.join(dir, "../../node_modules")).quiet()
   await $`tar -xf ../../node_modules/${watcher.replace("@parcel/", "parcel-")}-*.tgz -C ../../node_modules/${watcher} --strip-components=1`
 
-  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
+  const parserWorker = fs.realpathSync(
+    path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"),
+  )
+  const workerPath = "./src/cli/cmd/tui/worker.ts"
+
   await Bun.build({
     conditions: ["browser"],
     tsconfig: "./tsconfig.json",
@@ -61,10 +67,11 @@ for (const [os, arch] of targets) {
       execArgv: [`--user-agent=opencode/${Script.version}`, `--env-file=""`, `--`],
       windows: {},
     },
-    entrypoints: ["./src/index.ts", parserWorker, "./src/cli/cmd/tui/worker.ts"],
+    entrypoints: ["./src/index.ts", parserWorker, workerPath],
     define: {
       OPENCODE_VERSION: `'${Script.version}'`,
       OTUI_TREE_SITTER_WORKER_PATH: "/$bunfs/root/" + path.relative(dir, parserWorker),
+      OPENCODE_WORKER_PATH: workerPath,
       OPENCODE_CHANNEL: `'${Script.channel}'`,
     },
   })
diff --git a/packages/opencode/src/cli/cmd/tui/thread.ts b/packages/opencode/src/cli/cmd/tui/thread.ts
index 3fd998bc..05b4e9a4 100644
--- a/packages/opencode/src/cli/cmd/tui/thread.ts
+++ b/packages/opencode/src/cli/cmd/tui/thread.ts
@@ -8,6 +8,10 @@ import { bootstrap } from "@/cli/bootstrap"
 import path from "path"
 import { UI } from "@/cli/ui"
 
+declare global {
+  const OPENCODE_WORKER_PATH: string
+}
+
 export const TuiThreadCommand = cmd({
   command: "$0 [project]",
   describe: "start opencode tui",
@@ -55,7 +59,11 @@ export const TuiThreadCommand = cmd({
     // Resolve relative paths against PWD to preserve behavior when using --cwd flag
     const baseCwd = process.env.PWD ?? process.cwd()
     const cwd = args.project ? path.resolve(baseCwd, args.project) : process.cwd()
-    const workerPath = new URL("./worker.ts", import.meta.url).href
+    let workerPath = new URL("./worker.ts", import.meta.url).href
+
+    if (typeof OPENCODE_WORKER_PATH !== "undefined") {
+      workerPath = OPENCODE_WORKER_PATH
+    }
 
     try {
       process.chdir(cwd)
@@ -63,6 +71,7 @@ export const TuiThreadCommand = cmd({
       UI.error("Failed to change directory to " + cwd)
       return
     }
+
     await bootstrap(cwd, async () => {
       upgrade()
 
```

**Comment by paralin** [comment]
@kommander thanks I updated the PR. it works for me, I tested :)

File: packages/opencode/src/cli/cmd/tui/thread.ts (hunk 1 above)
Comment (paralin) [reply packages/opencode/src/cli/cmd/tui/thread.ts]: Fixed!

File: packages/opencode/src/cli/cmd/tui/thread.ts [hunk 2]
```diff
@@ -58,13 +62,21 @@ export const TuiThreadCommand = cmd({
       return piped ? piped + "\n" + args.prompt : args.prompt
     })()
 
-    const cwd = args.project ? path.resolve(args.project) : process.cwd()
+    // Resolve relative paths against PWD to preserve behavior when using --cwd flag
+    const baseCwd = process.env.PWD ?? process.cwd()
+    const cwd = args.project ? path.resolve(baseCwd, args.project) : process.cwd()
+    let workerPath = new URL("./worker.ts", import.meta.url).href
```
Comment (jerome-benoit) [inline packages/opencode/src/cli/cmd/tui/thread.ts]: Theoretically, Worker class is able to handle plain URL object. But I guess you hit a bug in bun that is not yet fixed.

**Comment by istarkov** [comment]
It's a bun bug 
here imo is more simple fix https://github.com/sst/opencode/pull/3764
based on comment here https://github.com/oven-sh/bun/issues/15981#issuecomment-2978577266

Easier to delete 2 lines when bun will fix the issue.

**Comment by jerome-benoit** [comment]
> It's a bun bug here imo is more simple fix #3764 based on comment here [oven-sh/bun#15981 (comment)]

But it does not address the main concern here.

**Comment by istarkov** [comment]
Ive just tested, it works in dev mode against my own repo and build is working

PS: anyway tested the other command, executing being in repo
PPS: Both are working

File: packages/opencode/src/cli/cmd/tui/thread.ts (hunk 2 above)
Comment (paralin) [reply packages/opencode/src/cli/cmd/tui/thread.ts]: I think I have fixed this with 646f4b6d48e540995bbb9078ecd9adffec3f0a29

**Comment by jerome-benoit** [comment]
> Ive just tested, it works in dev mode against my own repo and build is working

Some edge cases are not properly handled by your PR. The code here is trying the resolve cwd to handle most of them (while also consolidating worker files path definition).

File: packages/opencode/src/cli/cmd/tui/thread.ts (hunk 2 above)
Comment (jerome-benoit) [reply packages/opencode/src/cli/cmd/tui/thread.ts]: Since you're on it, you should really mention the bun bug URI to explain why that workaround to resolve cwd manually is currently needed

**Comment by istarkov** [comment]
Can you provide that edge cases? So I could learn

**Comment by paralin** [comment]
1. Bun bug: https://github.com/oven-sh/bun/issues/15981
2. `bun run --cwd packages/opencode`, the `process.cwd()` returns the `--cwd` value `packages/opencode`, not the directory the user ran "bun" within. This causes `path.resolve(args.project)` to resolve relative paths from the wrong base directory.

File: packages/opencode/src/cli/cmd/tui/thread.ts (hunk 2 above)
Comment (paralin) [reply packages/opencode/src/cli/cmd/tui/thread.ts]: @jerome-benoit squashed it & added the link + explanation

Comment (jerome-benoit) [reply packages/opencode/src/cli/cmd/tui/thread.ts]: Sorry, I mean in the code comment: so people do not remove it. That code should not be here in normal circumstance and people might remove it because of that. Keeping track of why it's here will reduce that probability ;)

**Comment by jerome-benoit** [comment]
> Can you provide that edge cases? So I could learn

It's a workaround for a code interpreter issue. We do not know what is the root cause in the interpreter: import code path resolution? worker code path resolution? worker env init code? generic path resolution issue (unlikely), ... Since you do not know, enforcing a robust cwd path resolution before is the safest way.

**Comment by istarkov** [comment]
I prefer to focus on an optimistic future. Imagine one day Bun fixes the issue, and all you have to do is remove two lines of code or much more in multiple files. It’s quite debatable whether sharing a variable between the build and the code actually makes things better - in both cases, you still need to search for the source. (It’s shared via define and ts will point you to the globals section.) 

> import code path resolution? worker code path resolution? worker env init code? generic path resolution issue (unlikely)

We’re just implementing a bug workaround. Both changes are the same, except here the path is shared through define.

In a pessimistic scenario, it’s still easy to detect the issue in any situation I can imagine. The code above doesn’t produce TypeScript or linting errors if the worker is moved.

I absolutely don’t mean to offend - that’s just how I see it. ;-)

**Comment by jerome-benoit** [comment]
> I prefer to focus on an optimistic future. Imagine one day Bun fixes the issue, and all you have to do is remove two lines of code or much more in multiple files. It’s quite debatable whether sharing a variable between the build and the code actually makes things better - in both cases, you still need to search for the source. (It’s shared via define and ts will point you to the globals section.)

Tunables single source of truth is a best practice.
Robust workaround implementation dealing with versioning and edge cases is also a best practice. 

I prefer to focus on building reliable software following documented best practices elaborated by people smarter than me since computer science has begun.

**Comment by kommander** [comment]
Thanks for both of your contributions! Keep it coming, appreciated.

**Comment by aspiers** [comment]
Gentle plea for the future: it would be super helpful if you could include documentation updates along with code changes.  I filed #6404 regarding the missing docs.  Thanks!
