### PR TITLE
fix: filter empty content blocks for Bedrock provider

### LINKED ISSUE #11210: Kimi K2 via AWS BEDROCK stops execution
### Description

I'm using Kimi K2 Thinking from bedrock and get the following error in plan mode:
`undefined: The content field in the Message object at messages.3 is empty. Add a ContentBlock object to the content field and try again.`

### Plugins

_No response_

### OpenCode version

_No response_

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by Tom-Ryder**
### Issue for this PR

Closes #11210

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

`normalizeMessages()` filters empty text/reasoning parts for `@ai-sdk/anthropic` but not `@ai-sdk/amazon-bedrock`. The Bedrock Converse API has the same constraint — empty content arrays cause "content field is empty" and invalid cache point errors that permanently break the session. Extended the existing guard to also cover Bedrock.

Note: this fixes the empty content filtering side of #11210. The separate Bedrock ConverseAPI tool call issues flagged in the thread will need a follow-up.

### How did you verify your code works?

- `bun turbo typecheck` passes
- Added 6 tests mirroring the existing anthropic empty content filtering suite, all pass
- Existing tests unchanged and passing

### Screenshots / recordings

N/A — backend logic change.

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### CODE REVIEW

**Comment by marcosvrs** [comment]
Tested this exact failure pattern in production usage with Bedrock Claude in OpenCode:\n\n`undefined: The content field in the Message object at messages.X is empty`\n\nI dug into the transform path and confirmed the root cause aligns with this PR: empty text/reasoning filtering currently runs for `@ai-sdk/anthropic` but not `@ai-sdk/amazon-bedrock`, so Bedrock Converse receives empty content arrays and rejects the request.\n\nFor Bedrock-only users, this is a hard blocker because there is no config-level workaround that preserves thinking behavior. Disabling thinking reduces frequency but is not an equivalent fix.\n\nWould appreciate prioritizing merge/release of this patch when possible - it unblocks a significant Bedrock Claude workflow.

File: packages/opencode/src/provider/transform.ts [hunk 1]
```diff
@@ -135,37 +135,31 @@ export namespace ProviderTransform {
...
-              ...msg,
-              content: filteredContent,
-              providerOptions: {
-                ...msg.providerOptions,
-                openaiCompatible: {
-                  ...(msg.providerOptions as any)?.openaiCompatible,
-                  [field]: reasoningText,
+      return msgs
+        .map((msg) => {
+          if (msg.role === "assistant" && Array.isArray(msg.content)) {
```
Comment (rekram1-node) [inline packages/opencode/src/provider/transform.ts]: why change this unrelated stuff?

File: packages/opencode/test/provider/transform.test.ts [hunk 2]
```diff
@@ -966,159 +866,241 @@ describe("ProviderTransform.message - anthropic empty content filtering", () =>
...
+    },
+    cost: { input: 0.45, output: 1.8, cache: { read: 0, write: 0 } },
+    limit: { context: 200000, output: 96000 },
+    status: "active",
+    options: {},
+    headers: {},
+  } as any
 
-  test("keeps non-text/reasoning parts even if text parts are empty", () => {
+  test("drops assistant message that has only reasoning parts", () => {
```
Comment (rekram1-node) [inline packages/opencode/test/provider/transform.test.ts]: hm im not sure if this one is correct

File: packages/opencode/src/provider/transform.ts [hunk 3]
```diff
@@ -51,7 +51,7 @@ export namespace ProviderTransform {
   ): ModelMessage[] {
     // Anthropic rejects messages with empty content - filter out empty string messages
     // and remove empty text/reasoning parts from array content
-    if (model.api.npm === "@ai-sdk/anthropic") {
+    if (model.api.npm === "@ai-sdk/anthropic" || model.api.npm === "@ai-sdk/amazon-bedrock") {
```
Comment (rekram1-node) [inline packages/opencode/src/provider/transform.ts:54]: why can't we just have this change +1 test for it, ill cleanup later cause we should be a bit better at doing this across the board but htere was a special case that caused errors in the past

Comment (Tom-Ryder) [reply packages/opencode/src/provider/transform.ts:54]: Removed. That test was for the interleaved block change which is now gone. Single test for the Bedrock guard now.

File: packages/opencode/test/provider/transform.test.ts (hunk 2 above)
Comment (Tom-Ryder) [reply packages/opencode/test/provider/transform.test.ts]: Removed. I was trying to cover a second path where the interleaved filter at line 136 could produce empty content arrays after stripping reasoning parts. But you're right, it's unrelated to the core empty content guard fix. Can be a separate PR if needed.

File: packages/opencode/src/provider/transform.ts (hunk 1 above)
Comment (Tom-Ryder) [reply packages/opencode/src/provider/transform.ts]: Done. Stripped it down to just this change + 1 test. The interleaved block change was addressing a second code path where reasoning-only messages could end up with empty content after stripping, but that's a separate concern. Removed it.

File: packages/opencode/test/provider/transform.test.ts (hunk 2 above)
Comment (rekram1-node) [reply packages/opencode/test/provider/transform.test.ts]: oh yeah separate would be good, I think I tried to solve this across the board in the past but didn't properly check `reasoning_details` and `reasoning_content` fields or something and it broke stuff. Ideally we circle back w/ the across the board solution to prevent these patches for individual providers but I just wanna be very throughout w/ across the board stuff cause it is so finicky
