### PR TITLE
fix(tui): update toast duration handling to use default value

### LINKED ISSUE #23394: Broken TUI Toast when Copying Text
### Description

When highlighting text to copy on the TUI the toast seems to be broken compared to previous versions and just acts like a blip.

### Plugins

None

### OpenCode version

1.14.17

### Steps to reproduce

1. Try to copy text by highlighting and check for the Toast

### Screenshot and/or share link

https://github.com/user-attachments/assets/20e43a9e-7f54-43e5-bab6-fc5ad20ec5b8

### Operating System

macOs

### Terminal

Ghostty

### LINKED ISSUE #23613: "Copied to clipboard" toast disappears almost immediately on macOS
### Description

After updating to `v1.14.19`, the "Copied to clipboard" popup/toast flashes for about a second and disappears almost immediately when highlighting text. In previous versions, the message stayed visible a bit longer.

### Plugins

_No response_

### OpenCode version

1.14.19

### Steps to reproduce

Highlight/select some text
Observe the toast duration

### Screenshot and/or share link

_No response_

### Operating System

macOS Tahoe 26.4.1

### Terminal

Ghostty 1.3.1

### PR DESCRIPTION
**Pull request by OpeOginni**
### Issue for this PR

Closes #23394
Closes #23613

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

This PR adds back a defualt duration value of `5000`, it got broken since the PR change https://github.com/anomalyco/opencode/commit/675a46e23e679c294355435584ae662a7c0903c7#diff-cc994057bfc51f2b10c6a0251f9dbffc10e875626473e48812cc49cd89ef57b9L59, removing the parse that would add the default originally.

### How did you verify your code works?

Tested on my local machine with the change added in.

### Screenshots / recordings

**BEFORE**

https://github.com/user-attachments/assets/387483dc-efbf-41f7-bdf5-416df46663b7

**AFTER**

https://github.com/user-attachments/assets/4190a834-3cd0-4730-96ee-60f2c61f010e

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### CODE REVIEW

File: packages/opencode/src/cli/cmd/tui/ui/toast.tsx [hunk 1]
```diff
@@ -56,8 +56,8 @@ function init() {
 
   const toast = {
     show(options: ToastOptions) {
-      const { duration, ...currentToast } = options
-      setStore("currentToast", currentToast)
+      const duration = options.duration ?? 5000
```
Comment (JohnTNP) [inline packages/opencode/src/cli/cmd/tui/ui/toast.tsx]: Looks good! If you have a second, do you think it'd be worth making a `DEFAULT_TOAST_DURATION` constant for that 5000?

Comment (OpeOginni) [reply packages/opencode/src/cli/cmd/tui/ui/toast.tsx]: Smart thinking yeah, prob should have done that

**Comment by ariane-emory** [comment]
Have not personally tested, but it looks pretty reasonable to me.
