### PR TITLE
fix(github-copilot): auto-route GPT-5+ models to Responses API

### LINKED ISSUE #5866: [BUG]: GitHub Copilot Responses API routing for GPT-5+
## Problem

When using the `github-copilot` provider, GPT-5+ models are currently routed through the Chat API. This prevents users from enabling Responses-API-only controls (eg. `reasoningEffort`, `reasoningSummary`) for those models, even when they are supported by the model and useful for agent behavior tuning.

This is especially noticeable for `github-copilot/gpt-5.*` where users expect to be able to configure reasoning parameters similarly to other OpenAI-compatible providers.

## Proposed Solution

Add an **opt-in** provider option to route supported Copilot models through the Responses API:

- New config flag: `provider.github-copilot.options.useResponsesApi: true`
- Behavior:
  - Always route `codex*` models through `sdk.responses(modelID)` (existing behavior)
  - If `useResponsesApi` is enabled and the model is **GPT-5 or later**, route through `sdk.responses(modelID)`
  - Otherwise, default to `sdk.chat(modelID)` (no behavior change by default)

Example config:

```json
{
  "provider": {
    "github-copilot": {
      "options": {
        "useResponsesApi": true
      }
    }
  }
}
```

## Future (Deprecation)

Once GitHub Copilot / VS Code enables Responses API usage broadly (the VS Code setting is currently labeled *Experimental*), this option can likely be deprecated and/or defaulted on for supported models to reduce configuration surface area.

## References

Current status of supported API route for provider `github-copilot`:

| Model | API Route |
|---|---|
| gpt-4.1 | chat |
| gpt-4o | chat |
| gpt-5 | responses |
| gpt-5-codex | responses |
| gpt-5-mini | chat |
| gpt-5.1 | responses |
| gpt-5.1-codex | responses |
| gpt-5.1-codex-max | responses |
| gpt-5.1-codex-mini | responses |
| gpt-5.2 | responses |

- VS Code UI (settings) relevant to this feature:
  - `GitHub > Copilot > Chat: Use Responses Api` (Experimental)
  - `GitHub > Copilot > Chat: Responses Api Reasoning Effort` (Experimental)
  - `GitHub > Copilot > Chat: Responses Api Reasoning Summary` (Experimental)

Screenshot of the VS Code settings panel showing the above Copilot settings.

Image

## Environment

- Repo: `sst/opencode` (dev)
- Platform observed: Windows (but the behavior is provider/model routing specific, not OS-specific)

### PR DESCRIPTION
**Pull request by christso**
Automatically routes supported GitHub Copilot models via the Responses API, enabling Responses-only controls (e.g. reasoningEffort/reasoningSummary) for GPT-5+.

- GPT-5+ models (excluding gpt-5-mini) automatically use Responses API
- No configuration required

Closes #5866

### CODE REVIEW

File: packages/opencode/src/provider/provider.ts [hunk 1]
```diff
@@ -91,26 +108,30 @@ export namespace Provider {
         options: {},
       }
     },
-    "github-copilot": async () => {
+    "github-copilot": async (input) => {
       return {
         autoload: false,
         async getModel(sdk: any, modelID: string, _options?: Record<string, any>) {
-          if (modelID.includes("codex")) {
```
Comment (rekram1-node) [inline packages/opencode/src/provider/provider.ts:123]: if they support it for all gpt-5 variants just change condition to modelID.includes("gpt-5")?

Comment (christso) [reply packages/opencode/src/provider/provider.ts:123]: gpt-5-mini is not supported and I was probably being overly conservative. Should I remove opt-in and just get all gpt-5 variants (excluding gpt-5-mini) to use responses API?

**Comment by rekram1-node** [comment]
and u said reasoning doesnt work through completions api? is that a copilot thing?

File: packages/opencode/src/provider/provider.ts (hunk 1 above)
Comment (christso) [reply packages/opencode/src/provider/provider.ts:123]: I've simplified the logic now. No opt-in. Includes all gpt-5 variants except gpt-5-mini (refer to https://github.com/sst/opencode/issues/5866 for reasoning).

**Comment by christso** [comment]
> and u said reasoning doesnt work through completions api? is that a copilot thing?

The reasoning fields are OpenAI specific. OpenCode currently use the response api for Codex only for GitHub Copilot. I'm not sure why we did that.  Probably because some user complained about GPT-5-mini not working, so we (erroneously) moved all GPT models back to chat completions API except Codex. I propose we enable it for all GitHub Copilot OpenAI models if they support it.

I also ran some evals on GitHub Copilot (see my [gist](https://gist.github.com/christso/63b4b25f608de231fa93686f351b2b7d)) and it appears Chat Completions API does perform some hidden reasoning (between low and medium). But the point of my PR is to make it transparent and configurable.

**Comment by rekram1-node** [comment]
> OpenCode currently use the response api for Codex only for GitHub Copilot. I'm not sure why we did that

Well github copilot ONLY allows access to the codex models through their responses api, and then for everything else is through chat completions api (with the exception that some models are on both)

Copilot also returns reasoning in a custom format, to properly parse that we need to switch to a custom chat completions client just like we do for responses (cause their responses format is kinda custom too)

**Comment by christso** [comment]
> > OpenCode currently use the response api for Codex only for GitHub Copilot. I'm not sure why we did that
> 
> Well github copilot ONLY allows access to the codex models through their responses api, and then for everything else is through chat completions api (with the exception that some models are on both)
> 
> Copilot also returns reasoning in a custom format, to properly parse that we need to switch to a custom chat completions client just like we do for responses (cause their responses format is kinda custom too)

Exactly - that's the rationale here. Responses API already has the parser built, so we get reasoning support without adding another custom client.

In my issue https://github.com/sst/opencode/issues/5866 I included the list of models and the API they support. My PR is based on that. I've been using gpt-5.2 extensively with medium to high thinking and it's a close substitute to Opus 4.5 (except slower), so it's beneficial to be able to allow plugins to set the reasoning effort.

| Model | API Route |
|---|---|
| gpt-4.1 | chat |
| gpt-4o | chat |
| gpt-5 | responses |
| gpt-5-codex | responses |
| gpt-5-mini | chat |
| gpt-5.1 | responses |
| gpt-5.1-codex | responses |
| gpt-5.1-codex-max | responses |
| gpt-5.1-codex-mini | responses |
| gpt-5.2 | responses |

**Comment by Coruscant11** [comment]
Hi @rekram1-node ! Seems like this PR may be quite related to my issue #6864
Thanks for your time guys

**Comment by SamPeng87** [comment]
Since it's been stuck without merging, I tried pulling a branch locally and applied your changes. The reasoning seems problematic; I'm using gpt-5.2. I've added the configuration.
```
"github-copilot": {
"models": {
"gpt-5.2": {
"options": {
"reasoningEffort": "medium",
"textVerbosity": "low",
"reasoningSummary": "auto",
"include": ["reasoning.encrypted_content"]
}
}
}
}
```
But it still seems to be erroring
```
Thinking: **Executing
"reasoning part mBMlS2wUynXnRUkj0u1EUxSGec1+DM/OARVprgXj2rwPE8KpyOp8Gei2/SVaauwWVR/IHgmeThMdJ2o4o4L0lfF6DNSohvyC61nOAX3C8EIKIVvqLylHtv6hvM6fERL5CdZbsU1dtJi4LC32AI/yND4LaDJc3ZdKhubfSs5GaBWJ+VJz/YKbcrJ1Kv8Qk5Jm++670CM2kjo8HyyTl8aR28igAS6JGLZXsn7qYIu5PG6Hpv/sndVRoxtKgAdGaYiZfmCL4IaX3UmloU+ay/kY1ovapKwIwLkfNNtG+2omUxyROZAfP6TwRx1K3hykoowAWdazZBb5VufA9bCXJmZ92jlUM0j0HuGlXpqA7+3u1jnVvMO8C7CUO4wEcq8Y+5KENs1vp1+11/ZsCrvreX08pA==:0 not found"
```

**Comment by christso** [comment]
> Since it's been stuck without merging, I tried pulling a branch locally and applied your changes. The reasoning seems problematic; I'm using gpt-5.2.

Thanks for the find @SamPeng87! It's fixed now: https://github.com/anomalyco/opencode/pull/5877/commits/894861c95bf6bb014250248bd181798bf25f9c61

File: packages/opencode/src/provider/provider.ts (hunk 1 above)
Comment (rekram1-node) [reply packages/opencode/src/provider/provider.ts:123]: All gpt models support it now, so just do the "gpt-5" check and we can merge

File: packages/opencode/src/provider/transform.ts [hunk 2]
```diff
@@ -484,7 +484,11 @@ export namespace ProviderTransform {
     const result: Record<string, any> = {}
 
     // openai and providers using openai package should set store to false by default.
-    if (input.model.providerID === "openai" || input.model.api.npm === "@ai-sdk/openai") {
+    if (
```
Comment (rekram1-node) [inline packages/opencode/src/provider/transform.ts:495]: do u need this? hmm

Comment (rekram1-node) [reply packages/opencode/src/provider/transform.ts:495]: for copilot? is that what vscode does too? or other copilot clients

Comment (christso) [reply packages/opencode/src/provider/transform.ts:495]: Refined the condition to use `api.npm === "@ai-sdk/github-copilot"` instead of `providerID.startsWith("github-copilot")` for consistency with the existing `api.npm === "@ai-sdk/openai"` check.

**TL;DR:** Removing the conditional would technically work (SDKs currently strip unknown options), but it introduces unnecessary overhead, future risk, and is semantically incorrect. Refactoring to a cleaner architecture is out of scope for this fix.

---

<details>
<summary>Details</summary>

**Why not just remove the conditional?**

While SDKs currently strip unknown `providerOptions` silently (Zod schemas without `.strict()`), removing the conditional is problematic:

- **Unnecessary overhead** — sending options that will be stripped is wasteful
- **Future risk** — if a provider adds `.strict()` validation or their API starts rejecting unknown fields, it would break
- **Relying on implementation details** — the current "strip unknown fields" behavior is not a guaranteed contract

**Why not refactor to a VS Code-style "caller decides" approach?**

VS Code uses a pass-through model where extensions decide what options to send. To achieve this in opencode would require significant architectural changes:

1. Move `store` logic out of `ProviderTransform.options()` (the centralized option builder)
2. Push the decision up to callers in `session/llm.ts` or higher
3. Or implement a capability flag system like pi-mono's `compat.supportsStore` with auto-detection

All of these are out of scope for what should be a one-line fix.

**Research findings:**

1. **VS Code** uses a pass-through approach where `providerOptions` are typed as `{ [name: string]: any }` with no filtering—but extensions decide what to send, they don't set options unconditionally.

2. **AI SDK behavior:** Both `@ai-sdk/anthropic` and `@ai-sdk/google` use Zod schemas to validate `providerOptions`. Since neither uses `.strict()`, unknown keys are silently stripped—but this is an implementation detail, not a contract.

3. **pi-mono** uses a cleaner `compat.supportsStore` capability flag with auto-detection—a better architecture but significant refactoring.

**Why keep the conditional:**
- **Semantic correctness** — only send OpenAI params to OpenAI-compatible providers
- **Consistency** — matches existing patterns in `transform.ts` for other provider-specific options (OpenRouter `usage.include`, Google `thinkingConfig`, ZhipuAI `thinking`, etc.)
- **Defensive programming** — don't rely on SDKs ignoring unknown fields
- **Minimal change** — works within current architecture without refactoring

</details>

File: packages/opencode/src/provider/provider.ts (hunk 1 above)
Comment (christso) [reply packages/opencode/src/provider/provider.ts:123]: E2E testing confirmed gpt-5-mini does NOT support the Responses API. GitHub Copilot's backend returns: `model gpt-5-mini is not supported via Responses API`. The exclusion must stay.
image

Comment (rekram1-node) [reply packages/opencode/src/provider/provider.ts:123]: That's strange cause it works for me and their api says it supports it

Comment (christso) [reply packages/opencode/src/provider/provider.ts:123]: OpenAI supports gpt-5-mini on Responses API, but GitHub Copilot does NOT. Are you testing against OpenAI directly (api.openai.com) or GitHub Copilot (api.githubcopilot.com)?

You can copy this curl command and run it with your own token. The API explicitly returns error code unsupported_api_for_model.
```
# Test: gpt-5-mini on GitHub Copilot Responses API
# Replace YOUR_TOKEN with your GitHub Copilot token from:
#   ~/.local/share/opencode/auth.json (github-copilot.refresh)

COPILOT_TOKEN="YOUR_TOKEN"

echo "=== Chat API (works) ===" && \
curl -s -X POST "https://api.githubcopilot.com/chat/completions" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${COPILOT_TOKEN}" \
-H "User-Agent: opencode/1.0.0" \
-H "Openai-Intent: conversation-edits" \
-d '{"model": "gpt-5-mini", "messages": [{"role": "user", "content": "Say hi"}], "max_tokens": 10}'

echo -e "\n\n=== Responses API (fails) ===" && \
curl -s -X POST "https://api.githubcopilot.com/responses" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${COPILOT_TOKEN}" \
-H "User-Agent: opencode/1.0.0" \
-H "Openai-Intent: conversation-edits" \
-d '{"model": "gpt-5-mini", "input": [{"role": "user", "content": [{"type": "input_text", "text": "Say hi"}]}]}'

Results:
┌──────────────────────────┬───────────────────────────────────────────────────────────┐
│           API            │                        gpt-5-mini                         │
├──────────────────────────┼───────────────────────────────────────────────────────────┤
│ Chat (/chat/completions) │ ✅ Works                                                  │
├──────────────────────────┼───────────────────────────────────────────────────────────┤
│ Responses (/responses)   │ ❌ "model gpt-5-mini is not supported via Responses API." │
└──────────────────────────┴───────────────────────────────────────────────────────────┘
```

Comment (rekram1-node) [reply packages/opencode/src/provider/provider.ts:123]: I'm testing directly w/ copilot and it does work and when I hit copilot endpoint to get their models list that works too, also discussed w/ multiple others and it worked for them as well

Comment (rekram1-node) [reply packages/opencode/src/provider/provider.ts:123]: but ig there is some oddity to it

Comment (christso) [reply packages/opencode/src/provider/provider.ts:123]: I'm on copilot enterprise, maybe it behaves differently.
