### PR TITLE
fix: prevent sparse spacing in hyphenated words

### LINKED ISSUE #621: Wrapping is off in terminal
Notice the newlines after `core` and `PRs`
Image

Here's the shared link https://opencode.ai/s/qWWhdXq0

### PR DESCRIPTION
**Pull request by monotykamary**
## Summary

This PR fixes the sparse spacing issue that occurs when displaying hyphenated words like 'claude-code-action' in both Assistant and User messages in the TUI. Fixes #621.

## Problem

Previously, hyphenated words would break at hyphens, creating sparse single-word lines that made the chat interface look broken and difficult to read.

Before:
image

## Solution

After:
image

- **Assistant messages**: Use non-breaking hyphens (U+2011) in markdown rendering to prevent word breaks at hyphens
- **User messages**: Apply non-breaking hyphens before word wrapping and styling
- **Textarea component**: Modified word boundary detection to treat hyphens as part of words
- **Width constraint**: Maintained 86 character width limit with precise calculations

## Changes Made

1. **packages/tui/internal/components/chat/message.go**: Updated user message rendering to use non-breaking hyphens
2. **packages/tui/internal/components/textarea/textarea.go**: Modified word boundary detection in textarea word wrapping
3. **packages/tui/internal/util/file.go**: Enhanced markdown rendering with hyphen handling

## Testing

- Verified both Assistant and User messages display correctly
- Confirmed 86 character width constraint is maintained
- Tested with various hyphenated words and phrases
- No visual regressions in existing functionality

This change significantly improves the readability of hyphenated content in the TUI without affecting any other functionality.

### CODE REVIEW

File: packages/tui/internal/components/chat/message.go [hunk 1]
```diff
@@ -196,17 +196,26 @@ func renderText(
 	case opencode.UserMessage:
 		ts = time.UnixMilli(int64(casted.Time.Created))
 		base := styles.NewStyle().Foreground(t.Text()).Background(backgroundColor)
-		words := strings.Fields(text)
+		// Apply non-breaking hyphens to prevent sparse breaks
+		textWithHyphens := strings.ReplaceAll(text, "-", "2011")
```
Comment (adamdotdevin) [inline packages/tui/internal/components/chat/message.go]: is this supposed to be `u2011`?

File: packages/tui/internal/components/chat/message.go [hunk 2]
```diff
@@ -196,17 +196,26 @@ func renderText(
...
-		text = strings.Join(words, "")
-		text = ansi.WordwrapWc(text, width-6, " -")
-		content = base.Width(width - 6).Render(text)
+		styledText := strings.Join(words, "")
+		
+		// Apply word wrapping
+		wrappedText := ansi.WordwrapWc(styledText, width-6, " ")
+		
+		// Restore regular hyphens
+		finalText := strings.ReplaceAll(wrappedText, "2011", "-")
```
Comment (adamdotdevin) [inline packages/tui/internal/components/chat/message.go]: again, `u2011`?

File: packages/tui/internal/util/file.go [hunk 3]
```diff
@@ -83,11 +83,24 @@ func Extension(path string) string {
 }
 
 func ToMarkdown(content string, width int, backgroundColor compat.AdaptiveColor) string {
-	r := styles.GetMarkdownRenderer(width-6, backgroundColor)
+	// Use precise width calculation to maintain 86 constraint
```
Comment (adamdotdevin) [inline packages/tui/internal/util/file.go]: what is `86 constraint`?

File: packages/tui/internal/util/file.go [hunk 4]
```diff
@@ -83,11 +83,24 @@ func Extension(path string) string {
...
+	renderWidth := width - 6 // Account for padding and borders
+	if renderWidth < 10 {
+		renderWidth = 10
+	}
```
Comment (adamdotdevin) [inline packages/tui/internal/util/file.go]: what's this for?

**Review by adamdotdevin — CHANGES_REQUESTED** [review]
just a few questions, i'd love to have this fixed, just need to understand the implementation a little better

File: packages/tui/internal/components/chat/message.go (hunk 1 above)
Comment (monotykamary) [reply packages/tui/internal/components/chat/message.go]: ah yes, my bad; let me add that back in

**Comment by monotykamary** [comment]
Now that you've pointed it out, I think there might be a more ergonomic way to do this 🤔 
also now that we're going for a stretched look

**Comment by monotykamary** [comment]
| Before | After |
| --- | ---|
| image | image |
