### PR TITLE
fix: opencode run crashing, and show errored tool calls in output

### LINKED ISSUE #14169: Bug: titlecase() crashes with TypeError when task() tool called without subagent_type
## Summary

`opencode` crashes with a `TypeError` when the LLM calls the `task()` tool without providing the `subagent_type` field, which is optional in the schema.

## Error

```
TypeError: undefined is not an object (evaluating 'str3.replace')
      at titlecase (src/util/locale.ts:3:12)
      at task (src/cli/cmd/run.ts:170:24)
      at loop (src/cli/cmd/run.ts:472:15)
```

## Root Cause

In `src/cli/cmd/run.ts` line 170:

```typescript
Locale.titlecase(info.input.subagent_type)
```

When the model calls `task()` without `subagent_type` (optional parameter), `info.input.subagent_type` is `undefined`. The `titlecase` function in `src/util/locale.ts` has no null/undefined guard:

```typescript
// src/util/locale.ts — current code
function titlecase(str) {
    return str.replace(/\b\w/g, (c) => c.toUpperCase());
    //         ^ crashes if str is undefined or null
}
```

## Reproduction

1. Use opencode with any LLM that may call the `task` tool without `subagent_type`
2. Run in a TypeScript project directory (increases likelihood of sub-agent delegation)
3. The crash occurs the first time `task()` is invoked without `subagent_type`

## Fix

Add a null guard to `titlecase()` in `src/util/locale.ts`:

```typescript
function titlecase(str: string | undefined): string {
    if (!str) return "";
    return str.replace(/\b\w/g, (c) => c.toUpperCase());
}
```

Or at the call site in `run.ts`:

```typescript
Locale.titlecase(info.input.subagent_type ?? "")
```

> **Note:** This appears to have been reported previously as issue #13933 and a fix was proposed in PR #13955. Documenting here in case it hasn't been merged yet in this fork.

## Workaround

A same-size binary patch can be applied to the compiled binary until an official fix ships. Full details and patch script available in this gist:

https://gist.github.com/bkataru/27caa1aeb746efb06f83127cfcc586b0

## Environment

| Component | Version |
|-----------|---------|
| opencode | v1.2.6 |
| oh-my-opencode | v3.7.3 |
| OS | Linux (Ubuntu 24.04) |
| Binary | bun-compiled |

### PR DESCRIPTION
**Pull request by rekram1-node**
fixes: #14169

### CODE REVIEW

File: packages/opencode/src/cli/cmd/run.ts [hunk 1]
```diff
@@ -168,12 +168,17 @@ function websearch(info: ToolProps<typeof WebSearchTool>) {
 }
 
 function task(info: ToolProps<typeof TaskTool>) {
-  const agent = Locale.titlecase(info.input.subagent_type)
-  const desc = info.input.description
-  const started = info.part.state.status === "running"
+  const input = info.part.state.input
+  const status = info.part.state.status
```
Comment (colinandres885-boop) [inline packages/opencode/src/cli/cmd/run.ts]: https://orcid.org/0009-0001-7396-026X
