### PR TITLE
fix: resolve symlinks in Instance cache to prevent duplicate contexts

### LINKED ISSUE #15482: Two server instances created when project path contains symlink, causing TUI to freeze on prompt
### Description

When the working directory is a symlink to another path, opencode spawns two state instances. Subsequent prompts appear to not be processed in the TUI (no message API calls logged), but are likely being handled by the shadow instance invisibly.

When i move to the folder directly without the symlink. And do the same: run `opencode .`, `/session` and select the session i was working on and try "test" prompt => works fine.

Ai helped me with doing the analysis and the title so take the title and hypotheses with enough grain of salt.

### Plugins

none that i know

### OpenCode version

1.2.15

### Steps to reproduce

Open opencode in a directory that is a symlink (e.g. ~/ssd → /media/.../ssd_storage), switch to an old session via /session, send a prompt — UI freezes.

```bash
$ ls -la ~/ssd
lrwxrwxrwx 1 myname myname 23 helmi  16 11:56 /home/myname/ssd -> /media/myname/ssd_storage
```

### Screenshot and/or share link

INFO  2026-02-28T18:33:12 +0ms service=server method=GET path=/path request
INFO  2026-02-28T18:33:12 +0ms service=server status=started method=GET path=/path request
INFO  2026-02-28T18:33:12 +0ms service=server status=completed duration=0 method=GET path=/path request
INFO  2026-02-28T18:33:12 +5ms service=server status=completed duration=9 method=GET path=/formatter request
INFO  2026-02-28T18:33:15 +3324ms service=server method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5 request
INFO  2026-02-28T18:33:15 +0ms service=server status=started method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5 request
INFO  2026-02-28T18:33:15 +1ms service=server url=http://opencode.internal/session/ses_362512ee7ffeu3OQz9LYI4nxG5 SEARCH
INFO  2026-02-28T18:33:15 +1ms service=server status=completed duration=2 method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5 request
INFO  2026-02-28T18:33:15 +0ms service=server method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/message request
INFO  2026-02-28T18:33:15 +0ms service=server status=started method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/message request
INFO  2026-02-28T18:33:15 +37ms service=server status=completed duration=37 method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/message request
INFO  2026-02-28T18:33:15 +14ms service=server method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/todo request
INFO  2026-02-28T18:33:15 +0ms service=server status=started method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/todo request
INFO  2026-02-28T18:33:15 +1ms service=server status=completed duration=1 method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/todo request
INFO  2026-02-28T18:33:15 +0ms service=server method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/diff request
INFO  2026-02-28T18:33:15 +0ms service=server status=started method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/diff request
INFO  2026-02-28T18:33:15 +1ms service=server status=completed duration=1 method=GET path=/session/ses_362512ee7ffeu3OQz9LYI4nxG5/diff request
INFO  2026-02-28T18:39:26 +371112ms service=default worker shutting down
INFO  2026-02-28T18:39:26 +4ms service=default disposing all instances
INFO  2026-02-28T18:39:26 +1ms service=bus type=* unsubscribing
INFO  2026-02-28T18:39:26 +0ms service=server event disconnected
INFO  2026-02-28T18:39:26 +1ms service=default directory=/media/myname/ssd_storage/project_collection_foo/app_bar disposing instance
INFO  2026-02-28T18:39:26 +0ms service=state key=/media/myname/ssd_storage/project_collection_foo/app_bar waiting for state disposal to complete
INFO  2026-02-28T18:39:26 +2ms service=state key=/media/myname/ssd_storage/project_collection_foo/app_bar state disposal completed
INFO  2026-02-28T18:39:26 +0ms service=default directory=/home/myname/ssd/project_collection_foo/app_bar disposing instance
INFO  2026-02-28T18:39:26 +0ms service=state key=/home/myname/ssd/project_collection_foo/app_bar waiting for state disposal to complete
INFO  2026-02-28T18:39:26 +1ms service=state key=/home/myname/ssd/project_collection_foo/app_bar state disposal completed

### Operating System

Ubuntu 22.04

### Terminal

Gnome terminal

### LINKED ISSUE #16647: Symlinked project directories break after 8a95be4 (realpath resolution)
### Description
Commit [8a95be4](https://github.com/anomalyco/opencode/commit/8a95be492d460050ab53161be7185dc1c1783eef) introduced `Filesystem.resolve()` which calls `realpathSync.native()` to canonicalize the project directory. This dereferences symlinks. The resolve call was added to the server request middleware (`server.ts`), the instance cache (`instance.ts`), and the TUI entry point (`thread.ts`). The app frontend (`directory-layout.tsx`) was also updated to call `/path`, detect the resolved directory, and redirect the URL slug to match.

When OpenCode is launched from a directory that is (or is inside) a symlink, the client initially sends the symlink path but the server resolves it to the real target path. This creates a mismatch: the instance is keyed by the real path, but the frontend may still reference the symlink path in some flows. The result is that sessions are broken and AI output is not visible. Launching from the real (non-symlink) path works fine.

### Plugins
None

### OpenCode version
Unknown; regression introduced by 8a95be4

### Steps to reproduce
1. Create a symlink to a repo: `ln -s /path/to/real/repo /path/to/link/repo`
2. `cd /path/to/link/repo` (confirm `pwd` shows the symlink path).
3. Start OpenCode (TUI or app).
4. Create/open a session and send a prompt.
5. Observe: session UI appears broken and AI output is not visible.
6. Repeat from the real path (`cd /path/to/real/repo`) and note it works normally.

### Screenshot and/or share link
N/A

### Operating System
macOS 26.3.1 (Build 25D2128)

### Terminal
Ghostty 1.2.3 (stable)

### LINKED ISSUE #16659: Bare catch in Filesystem.resolve() swallows non-ENOENT errors
### Description

The `try/catch` in `Filesystem.resolve()` (introduced in #16651) catches *all* exceptions from `realpathSync`, not just `ENOENT`. Errors like `EACCES` (permission denied), `ELOOP` (too many symlink levels), and `ENOTDIR` (component is not a directory) are silently swallowed, and the function falls back to the unresolved path.

This means:

- An `EACCES` on a symlink target silently resolves to the symlink path instead of surfacing the permission error
- An `ELOOP` (symlink cycle) silently resolves to the unresolvable symlink path instead of alerting the user
- Both could lead to `Instance.provide()` creating a context keyed on a non-canonical path, re-introducing the duplicate-instance class of bugs for those edge cases

The codebase already has an `isEnoent()` type guard at `filesystem.ts:50` used elsewhere. The fix is to narrow the catch:

```ts
export function resolve(p: string): string {
  const resolved = pathResolve(windowsPath(p))
  try {
    return normalizePath(realpathSync(resolved))
  } catch (e) {
    if (isEnoent(e)) return normalizePath(resolved)
    throw e
  }
}
```

### Steps to reproduce

1. Create a symlink cycle: `ln -s a b && ln -s b a`
2. Or create a symlink to a permission-denied directory
3. Run `opencode` from a path involving that symlink
4. Observe that the error is silently swallowed instead of surfaced

### Operating System

All platforms

### PR DESCRIPTION
**Pull request by jmylchreest**
### Issue for this PR

Fixes #16647
Fixes #15482
Fixes #16659
Related: #16522, #16641

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

`Filesystem.resolve()` used `path.resolve()` which normalizes `.`/`..` segments but does **not** resolve symlinks. When opencode runs from a symlinked directory, `Instance.provide()` creates duplicate contexts for the same physical directory because two different path strings produce two separate cache entries.

Because the `Bus` pub/sub system is Instance-scoped (via `Instance.state()`), events published on one Instance (where the LLM session runs) are never received by subscribers on the other Instance (where the SSE endpoint listens). This causes a completely blank TUI after sending prompts.

**Fix:** Move symlink resolution (`realpathSync`) into `Filesystem.resolve()` so all callers benefit — not just `Instance.provide()` and `Instance.reload()`. Falls back to the unresolved path only for `ENOENT` (path doesn't exist yet); all other errors (`EACCES`, `ELOOP`, `ENOTDIR`) are rethrown to avoid silently masking broken paths.

This is complementary to #16641 which canonicalizes at the caller (thread.ts) level.

### How did you verify your code works?

- Reproduced the bug by running opencode from `~/src-office` (a symlink to `~/dtkr4-cnjjf/...`)
- Confirmed blank TUI after sending prompt (events never bridged between instances)
- Applied fix, rebuilt, and verified prompts and responses work correctly
- Added tests for symlink resolution, non-existent path fallback, ELOOP, EACCES, and ENOTDIR
- `bun test test/util/filesystem.test.ts` — 55 tests pass (including 5 new)
- `bun tsc --noEmit` — no type errors

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### CODE REVIEW

File: packages/opencode/src/cli/cmd/tui/context/sync.tsx [hunk 1]
```diff
@@ -471,10 +471,35 @@ export const { use: useSync, provider: SyncProvider } = createSimpleContext({
               if (match.found) draft.session[match.index] = session.data!
               if (!match.found) draft.session.splice(match.index, 0, session.data!)
               draft.todo[sessionID] = todo.data ?? []
-              draft.message[sessionID] = messages.data!.map((x) => x.info)
+
+              // Merge fetched messages with any already delivered by real-time
```
Comment (Hona) [inline packages/opencode/src/cli/cmd/tui/context/sync.tsx]: why?

Comment (jmylchreest) [reply packages/opencode/src/cli/cmd/tui/context/sync.tsx]: Apparently my assistant just got a bit overzealous after I raised the correct PR and went for a drink! Just sorting this branch but the draft merge fix was due to an SSE race condition I was hitting where occasional SSE messages were lost.

It's highly likely they're masked by fixing the realpath/symlink bug, they're 2 separate issues but I hit both while debugging the symlink one.

File: packages/opencode/src/project/instance.ts [hunk 2]
```diff
@@ -62,7 +63,8 @@ function track(directory: string, next: Promise<Context>) {
 
 export const Instance = {
   async provide<R>(input: { directory: string; init?: () => Promise<any>; fn: () => R }): Promise<R> {
-    const directory = Filesystem.resolve(input.directory)
+    // Resolve symlinks so the same physical directory always maps to one Instance.
+    const directory = Filesystem.resolve(fs.realpathSync(input.directory))
```
Comment (brndnblck) [inline packages/opencode/src/project/instance.ts]: `fs.realpathSync()` throws `ENOENT` if the path doesn't exist. `Filesystem.resolve()` (via `path.resolve()`) previously handled non-existent paths gracefully.

This is a behavioral change that could surface as an unhandled exception in edge cases (e.g., a directory removed between CLI invocation and `Instance.provide()`).

Consider guarding:

```suggestion
    const directory = Filesystem.resolve(fs.existsSync(input.directory) ? fs.realpathSync(input.directory) : input.directory)
```

Or wrapping in try/catch to fall back to the unresolved path, matching the pattern already used in `normalizePath()`:

```ts
function realpath(p: string): string {
  try {
    return fs.realpathSync(p)
  } catch {
    return p
  }
}
```

File: packages/opencode/src/project/instance.ts [hunk 3]
```diff
@@ -104,7 +106,7 @@ export const Instance = {
     return State.create(() => Instance.directory, init, dispose)
   },
   async reload(input: { directory: string; init?: () => Promise<any>; project?: Project.Info; worktree?: string }) {
-    const directory = Filesystem.resolve(input.directory)
+    const directory = Filesystem.resolve(fs.realpathSync(input.directory))
```
Comment (brndnblck) [inline packages/opencode/src/project/instance.ts]: Same `realpathSync` throw risk as `provide()` above — should use the same guard pattern.

```suggestion
    const directory = Filesystem.resolve(fs.existsSync(input.directory) ? fs.realpathSync(input.directory) : input.directory)
```

File: packages/opencode/src/project/instance.ts [hunk 4]
```diff
@@ -5,6 +5,7 @@ import { State } from "./state"
 import { iife } from "@/util/iife"
 import { GlobalBus } from "@/bus/global"
 import { Filesystem } from "@/util/filesystem"
+import fs from "fs"
```
Comment (brndnblck) [inline packages/opencode/src/project/instance.ts]: Since symlink resolution is now an explicit concern of `Instance`, it might be cleaner to push this into `Filesystem.resolve()` itself — it already handles Windows path translation and `normalizePath`. That way all callers get symlink resolution, not just `provide()` and `reload()`.

Something like:
```ts
// filesystem.ts
export function resolve(p: string): string {
  const resolved = pathResolve(windowsPath(p))
  try {
    return normalizePath(realpathSync(resolved))
  } catch {
    return normalizePath(resolved)
  }
}
```

This would also cover `server.ts` middleware and `thread.ts`, which both call `Filesystem.resolve()` independently and could theoretically still produce non-canonical paths.

File: packages/opencode/src/project/instance.ts [hunk 5]
```diff
@@ -62,7 +63,8 @@ function track(directory: string, next: Promise<Context>) {
 
 export const Instance = {
   async provide<R>(input: { directory: string; init?: () => Promise<any>; fn: () => R }): Promise<R> {
-    const directory = Filesystem.resolve(input.directory)
+    // Resolve symlinks so the same physical directory always maps to one Instance.
```
Comment (brndnblck) [inline packages/opencode/src/project/instance.ts]: This fix has no test coverage. A symlink-specific test for `Instance.provide()` on macOS/Linux would prevent regressions — e.g.:

```ts
test("preserves single instance for symlinked directory", async () => {
  if (process.platform === "win32") return
  await using tmp = await tmpdir({ git: true, config: { model: "test/model" } })
  const link = tmp.path + "-symlink"
  await fs.symlink(tmp.path, link)
  try {
    await Instance.provide({
      directory: link,
      fn: async () => {
        const config = await Config.get()
        expect(config.model).toBe("test/model")
      },
    })
  } finally {
    await fs.unlink(link).catch(() => {})
  }
})
```

The `win32` guard is intentional — `fs.symlink` on Windows requires `SeCreateSymbolicLinkPrivilege` (admin) and the bug manifests on macOS/Linux where symlinks are common.

**Review by brndnblck — COMMENTED** [review]
Review migrated from #16650 — the slimmed-down scope here is much appreciated. Comments on the `instance.ts` changes still apply.

File: packages/opencode/src/cli/cmd/tui/context/sync.tsx (hunk 1 above)
Comment (jmylchreest) [reply packages/opencode/src/cli/cmd/tui/context/sync.tsx]: fixed.

**Comment by brndnblck** [comment]
Thank you for jumping on this @jmylchreest

File: packages/opencode/src/project/instance.ts (hunk 4 above)
Comment (jmylchreest) [reply packages/opencode/src/project/instance.ts]: Yes I agree this is the real fix - just looking at how best to address that and will update the PR

**Comment by jmylchreest** [comment]
Updated to move this logic into resolve(), it's working from what I can see in all my local tests, plus the test condition I think covers it. I've not tested under WSL, I can't, nor MacOS directly - but I trust they're OK.

File: packages/opencode/src/project/instance.ts (hunk 5 above)
Comment (jmylchreest) [reply packages/opencode/src/project/instance.ts]: agreed, implemented just this.

File: packages/opencode/src/project/instance.ts (hunk 2 above)
Comment (jmylchreest) [reply packages/opencode/src/project/instance.ts]: implemented it as a catch in resolve()

File: packages/opencode/src/project/instance.ts (hunk 3 above)
Comment (jmylchreest) [reply packages/opencode/src/project/instance.ts]: no longer applicable - moved into resolve()

**Comment by brndnblck** [comment]
I'm validating on MacOS right now and I'll post here in a moment with results.

**Comment by brndnblck** [comment]
Confirming this resolves the issue on MacOS and the full test suite passes 🎉

**Comment by brndnblck** [comment]
I added #16659 and #16660 related to this PR (however, pre-existing) but I don't know if we want to try and address them in the same push or keep this fix localized since its impacting all MacOS users using symlinks.

The improvement in #16661 can definitely be shipped separately.

**Comment by jmylchreest** [comment]
https://github.com/anomalyco/opencode/issues/16659 I think makes sense to add, I'll push an update to the branch to test now. I personally think 16660 is a separate issue.

**Comment by jmylchreest** [comment]
raised https://github.com/anomalyco/opencode/pull/16665 which should resolve #16660 , depends on this PR to be applied as well to be reliable.
