### PR TITLE
fix: display errors when using `opencode run ...`

### LINKED ISSUE #752: `opencode run` does not output any errors
Not sure if this is by design or not but if I encounter an error when using `opencode run ...` that error is completely hidden. I feel like most people would probably want to see the error if there was one?

### PR DESCRIPTION
**Pull request by rekram1-node**
Fixes: #752

Example:

Screenshot 2025-07-08 at 9 25 56 AM

### CODE REVIEW

File: packages/opencode/src/session/index.ts [hunk 1]
```diff
@@ -99,6 +99,7 @@ export namespace Session {
     Error: Bus.event(
       "session.error",
       z.object({
+        sessionID: z.string().optional(),
```
Comment (rekram1-node) [inline packages/opencode/src/session/index.ts:102]: optional because mcp also emits these errors but that is at the global level not necessarily related to this session. Maybe we want to show all errors tho and not just session specific, just seemed weird having the mcp errors from the weather tool that is defined in opencode.json
