### PR TITLE
fix(app): support anthropic models on azure cognitive services

### LINKED ISSUE #5294: claude-opus-4.5 on azure unusable
### Description

Regardless of which azure I try, this is the result. (azure / cognitive services)

Image

### OpenCode version

1.0.138

### Steps to reproduce

- /models -> select claude-opus-4.5 
- write prompt -> instant error. 

### Screenshot and/or share link

_No response_

### Operating System

windows 11 / WSL2

### Terminal

vscode built in

### PR DESCRIPTION
**Pull request by uanandaraja**
Fixes https://github.com/sst/opencode/issues/5294

When using Azure Cognitive Services with Claude/Anthropic models, this automatically switches to @ai-sdk/anthropic with the appropriate Azure baseURL.

Users can now configure Anthropic models under the azure-cognitive-services provider:
```json
{
  "provider": {
    "azure-cognitive-services": {
      "models": {
        "claude-opus-4-5": { "id": "claude-opus-4-5" }
      }
    }
  }
}
```

With env vars:
- AZURE_COGNITIVE_SERVICES_RESOURCE_NAME
- AZURE_COGNITIVE_SERVICES_API_KEY

Screenshot 2026-01-14 at 09 43 10

### CODE REVIEW

**Comment by rekram1-node** [comment]
life saver

**Comment by uanandaraja** [comment]
what to do now? @rekram1-node 

all good?

**Comment by rekram1-node** [comment]
Sorry I saw this meant to merge, then couldnt find it again

File: packages/opencode/src/session/llm.ts [hunk 1]
```diff
@@ -138,30 +130,12 @@ export namespace LLM {
           params.options,
           input.model.limit.output,
           OUTPUT_TOKEN_MAX,
+          input.model.providerID,
+          input.model.api.id,
```
Comment (rekram1-node) [inline packages/opencode/src/session/llm.ts]: Let's clean this up, just pass input.model instead of 4 different fields from the model

Comment (uanandaraja) [reply packages/opencode/src/session/llm.ts]: should be done i think

Comment (uanandaraja) [reply packages/opencode/src/session/llm.ts]: Screenshot 2026-01-17 at 02 00 55

still working as well

File: packages/opencode/src/provider/transform.ts [hunk 2]
```diff
@@ -605,16 +636,27 @@ export namespace ProviderTransform {
...
+    options: Record<string, any>,
+    arg3: number,
+    arg4?: number,
   ): number {
+    const model = typeof arg1 === "object" ? arg1 : null
+    const npm = model ? model.api.npm : (arg1 as string)
+    const modelLimit = model ? model.limit.output : arg3
+    const globalLimit = model ? arg3 : arg4!
     const modelCap = modelLimit || globalLimit
     const standardLimit = Math.min(modelCap, globalLimit)
```
Comment (rekram1-node) [inline packages/opencode/src/provider/transform.ts:658]: Accidentally merged and had to revert, but what's going on in here? This look super messy why is it a union for model type?

Comment (uanandaraja) [reply packages/opencode/src/provider/transform.ts:658]: thats my bad tbh, just tried to make things work without considering the cleanliness

another pr attempt here: https://github.com/anomalyco/opencode/pull/9000

thanks!

**Comment by kevinzhg** [comment]
is this also fix the azure foundry, i still see the error when using azure, https://your-resource.services.ai.azure.com/anthropic/v1/messages, TypeError: sdk.responses is not a function. (In 'sdk.responses(modelID)', 'sdk.responses' is undefined)
