### PR TITLE
fix(opencode): add input limit for compaction

### LINKED ISSUE #7705: Default Codex context length not matching Pro plan
### Description

In the code, the context length for GPT 5.2 codex shows 400,000 tokens, which is technically correct for the API, but on the pro plan for ChatGPT, I believe you only get like 250 to 260, something like that. So, if the average user signs up with ChatGPT and uses it, they are likely to hit a context error, which forces compaction. So, it would make sense to maybe detect if it's a ChatGPT versus an API integration, and then automatically configure the defaults, maybe?

### Plugins

_No response_

### OpenCode version

1.1.111

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by brandon93s**
### What does this PR do?

- Add support for the `input` limit from models.dev
- Adds dedicated input limit for codex 5.2
- Closes #7705
- See https://github.com/anomalyco/models.dev/pull/642
- See https://github.com/anomalyco/models.dev/pull/646, 5.2 is now upstream

### How did you verify your code works?

- Tested with several large sessions via `bun dev` to confirm compaction triggers

### CODE REVIEW

File: packages/opencode/src/session/compaction.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export namespace SessionCompaction {
     if (context === 0) return false
     const count = input.tokens.input + input.tokens.cache.read + input.tokens.output
     const output = Math.min(input.model.limit.output, SessionPrompt.OUTPUT_TOKEN_MAX) || SessionPrompt.OUTPUT_TOKEN_MAX
-    const usable = context - output
+    const usable = input.model.limit.input || context - output
```
Comment (bndnsmth) [inline packages/opencode/src/session/compaction.ts:37]: If an input limit is provided, it's always the usable limit.  This can be less than context - output.

**Comment by brandon93s** [comment]
Auto-compaction now triggers based on the optional input limit.

There is a separate issue (I believe with all models) where the next outgoing message can overrun context/input limits.  In this scenario, the error should be caught with an auto-compaction running on thread history, and then a retry of the latest message occurring.  Perhaps integrated into `SessionRetry.retryable` with a force auto-compaction.  I won't attempt that in this PR.

File: packages/opencode/src/plugin/codex.ts [hunk 2]
```diff
@@ -361,38 +361,6 @@ export async function CodexAuthPlugin(input: PluginInput): Promise<Hooks> {
           }
         }
```
Comment (bndnsmth) [inline packages/opencode/src/plugin/codex.ts:363]: See https://github.com/anomalyco/models.dev/pull/646, this is now upstream including `limit.input`

**Comment by rekram1-node** [comment]
What a G

**Comment by rekram1-node** [comment]
> Auto-compaction now triggers based on the optional input limit.
> 
> There is a separate issue (I believe with all models) where the next outgoing message can overrun context/input limits. In this scenario, the error should be caught with an auto-compaction running on thread history, and then a retry of the latest message occurring. Perhaps integrated into `SessionRetry.retryable` with a force auto-compaction. I won't attempt that in this PR.

Yeah i mean this is awesome so thank you! Interesting idea would like to see it

**Comment by greggh** [comment]
Can this be an option to deal with models that get a bit weird or just plain broken long before their context window ends? The zai coding plan really starts to degrade fast into errors for a lot of us (See other threads) around 120k context. It would be interesting to be able to set this limit to 120k and have it auto compact at that point for that model.

**Comment by brandon93s** [comment]
@greggh the input limit is available in the config.  You could provide a custom model config:

```
"providerId": {
    "models": {
      "modelId": {
        "limit": { "input": 120000, "context": 200000 },
      },
    },
  },
```
