### PR TITLE
fix: support scoped npm plugins

### LINKED ISSUE #3392: [bug] Add scoped npm package as plugin shows error on startup
### Description

If I add a scoped npm package as a plugin(@gkzhb/opencode-skills
), I cannot start opencode, showing
```
Error: Unexpected error, check log file at /Users/bytedance/.local/share/opencode/log/2025-10-23T181629.log for more details

error: Cannot find module '/Users/bytedance/.cache/opencode/node_modules' from '/$bunfs/root/index.js'

```
Then I try to publish the same code but as not scoped `opencode-skills-gkzhb` package, it works.

Error log:
```
INFO  2025-10-23T18:28:18 +62ms service=default version=0.15.13 args=[] opencode
INFO  2025-10-23T18:28:18 +0ms service=project directory=/Users/bytedance/.config/opencode fromDirectory
INFO  2025-10-23T18:28:18 +6ms service=config path=/Users/bytedance/.config/opencode/config.json loading
INFO  2025-10-23T18:28:18 +0ms service=config path=/Users/bytedance/.config/opencode/opencode.json loading
INFO  2025-10-23T18:28:18 +0ms service=config path=/Users/bytedance/.config/opencode/opencode.jsonc loading
INFO  2025-10-23T18:28:18 +8ms service=config path=/Users/bytedance/.config/opencode/opencode.jsonc loading
INFO  2025-10-23T18:28:18 +1ms service=bun cmd=["/Users/bytedance/.local/share/pnpm/global/5/.pnpm/opencode-darwin-arm64@0.15.13/node_modules/opencode-darwin-arm64/bin/opencode","add","@opencode-ai/plugin@0.15.13","--exact"] cwd=/Users/bytedance/.config/opencode running
INFO  2025-10-23T18:28:18 +5ms service=bun cmd=["/Users/bytedance/.local/share/pnpm/global/5/.pnpm/opencode-darwin-arm64@0.15.13/node_modules/opencode-darwin-arm64/bin/opencode","add","@opencode-ai/plugin@0.15.13","--exact"] cwd=/Users/bytedance/.opencode running
INFO  2025-10-23T18:28:18 +1ms service=plugin path=@gkzhb/opencode-skills loading plugin
INFO  2025-10-23T18:28:18 +3ms service=bun pkg= version=gkzhb/opencode-skills installing package using Bun's default registry resolution
INFO  2025-10-23T18:28:18 +0ms service=bun cmd=["/Users/bytedance/.local/share/pnpm/global/5/.pnpm/opencode-darwin-arm64@0.15.13/node_modules/opencode-darwin-arm64/bin/opencode","add","--force","--exact","--cwd","/Users/bytedance/.cache/opencode","@gkzhb/opencode-skills"] cwd=/Users/bytedance/.cache/opencode running
INFO  2025-10-23T18:28:19 +255ms service=bun code=0 stdout=bun add v1.3.0 (b0a6feca)

installed @opencode-ai/plugin@0.15.13

[3.00ms] done
 stderr=Saved lockfile
 done
INFO  2025-10-23T18:28:19 +255ms service=bun code=0 stdout=bun add v1.3.0 (b0a6feca)

installed @opencode-ai/plugin@0.15.13

[3.00ms] done
 stderr=Saved lockfile
 done
INFO  2025-10-23T18:28:19 +325ms service=bun code=0 stdout=bun add v1.3.0 (b0a6feca)

+ @ai-sdk/openai-compatible@1.0.22
+ opencode-anthropic-auth@0.0.2
+ opencode-copilot-auth@0.0.3

installed @gkzhb/opencode-skills@0.0.4

35 packages installed [162.00ms]
 stderr=Resolving dependencies
Resolved, downloaded and extracted [1]
Saved lockfile
 done
ERROR 2025-10-23T18:28:19 +6ms service=default name=ResolveMessage message=Cannot find module '/Users/bytedance/.cache/opencode/node_modules' from '/$bunfs/root/index.js' code=ERR_MODULE_NOT_FOUND specifier=/Users/bytedance/.cache/opencode/node_modules referrer=/$bunfs/root/index.js importKind=import-statement fatal
```

The weird thing is that `~/.cache/opencode/package.json` gets wrong after adding scoped npm plugin:
```json
{
  "dependencies": {
    "opencode-copilot-auth": "0.0.3",
    "opencode-anthropic-auth": "0.0.2",
    "@ai-sdk/openai-compatible": "latest",
    "": "gkzhb/opencode-skills"
  }
}
```

### OpenCode version

0.15.13

### Steps to reproduce

1.  Add npm plugin `@gkzhb/opencode-skills` in `opencode.json` eg. 
```json
{
  "plugin": [
    "@gkzhb/opencode-skills"
  ]
}
```
2. Start  opencode

### Screenshot and/or share link

Image

### Operating System

macOS 26.0.1

### Terminal

kitty

### PR DESCRIPTION
**Pull request by riatzukiza**
Scoped Plugin Bug
- Loader currently does plugin.split("@") (packages/opencode/src/plugin/index.ts:37), so a scoped name like @promethean-os/opencode-openai-codex-auth becomes pkg === "" and version === "promethean-os/opencode-openai-codex-auth".  
- BunProc.install then records that empty package key in the cache manifest (packages/opencode/src/bun/index.ts:60-94), producing "": "promethean-os/opencode-openai-codex-auth" and never installing the real module. The follow-up import resolves to /home/err/.cache/opencode/node_modules, triggering the “Cannot find module …” error you’re seeing.
- Parse plugin strings from the rightmost @ (or use npm-package-arg) so scoped packages stay intact, e.g. const at = plugin.lastIndexOf("@"); const pkg = at > 0 ? plugin.slice(0, at) : plugin; const version = at > 0 ? plugin.slice(at + 1) : "latest";.
- After patching, clear ~/.cache/opencode and restart so the dependency file is regenerated with the correct scoped package key.
Next step: adjust the loader parsing logic and rebuild; rerun with the scoped plugin to confirm it resolves.

closes: #3392

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -11,3 +11,5 @@ playground
 tmp
 dist
 .turbo
+**/.serena
```
Comment (riatzukiza) [inline .gitignore:14]: I added these because my bot would have dumped a load of memory files you may not want, and this is a common/popular agent framework that people should be able to/allowed to use on this project with out polluting the git.

File: packages/opencode/src/cli/cmd/tui/component/prompt/autocomplete.tsx [hunk 2]
```diff
@@ -385,7 +386,7 @@ export function Autocomplete(props: {
             const charBeforeCursor =
               cursorOffset === 0
                 ? undefined
-                : props.input().getTextRange(cursorOffset - 1, cursorOffset)
+                : props.input().plainText.slice(cursorOffset - 1, cursorOffset)
```
Comment (riatzukiza) [inline packages/opencode/src/cli/cmd/tui/component/prompt/autocomplete.tsx]: There was a typeerror,
