### PR TITLE
fix: make bash tool respect $SHELL

### LINKED ISSUE #3479: Opencode bash tool spawn user commands using `/bin/sh` what is not bash :-)
### Description

The issue seems like is in the following lines

https://github.com/sst/opencode/blob/dev/packages/opencode/src/tool/bash.ts#L149-L154

Here - `shell: true`

> **shell **- If true, runs command inside of a shell. Uses '/bin/sh' on Unix, and process.env.ComSpec on Windows. A different shell can be specified as a string. 

I'm expecting from bash tools to execute at least bash, or default `process.env.SHELL` but  `sh` feels pretty outdated for me. 

Something like this feels more suitable (or check bash existance and use it if it exists in the PATH)

```ts
const defaultShell = process.platform === "win32"
  ? true // process.env.ComSpec on Windows
  : process.env.SHELL ?? true // $SHELL - *default shell for new sessions* if set, otherwise /bun/sh

const proc = spawn(params.command, {
  // use the user's login shell (or sensible fallback) rather than the system /bin/sh default
  shell: defaultShell,
  cwd: Instance.directory,
  stdio: ["ignore", "pipe", "pipe"],
  detached: process.platform !== "win32",
})
```

### OpenCode version

0.15.18

### Steps to reproduce

In opencode write following prompt 

---
Run following bash command
```
pid=$$
echo "$(ps -p "$pid" -o comm=)"
```

The result is 

`/bin/sh` on linux

---

### Screenshot and/or share link

Share links doesn't work for me for unknown reason

### Operating System

MacOs

### Terminal

ITERM 2

### PR DESCRIPTION
**Pull request by istarkov**
For spawn: 
- Nothing changes for windows users.
- Uses $SHELL env variable - *default shell for new sessions* if set, othewise fallback on previous /bin/sh behaviour

Fixes #3479

### CODE REVIEW

**Comment by veracioux** [comment]
@istarkov @rekram1-node I feel like we should update the system prompt or tool description to tell the LLM what shell will be used. Especially for windows. The tool is called bash after all.

File: packages/opencode/src/tool/bash.ts [hunk 1]
```diff
@@ -147,7 +147,10 @@ export const BashTool = Tool.define("bash", {
     }
 
     const proc = spawn(params.command, {
-      shell: true,
+      shell:
+        process.platform === "win32"
+          ? true // process.env.ComSpec on Windows
+          : (process.env.SHELL ?? true), // $SHELL - *default shell for new sessions* if set, otherwise /bun/sh
```
Comment (geril07) [inline packages/opencode/src/tool/bash.ts]: `/bun/sh` -> `/bin/sh`?

**Comment by istarkov** [comment]
> @istarkov @rekram1-node I feel like we should update the system prompt or tool description to tell the LLM what shell will be used. Especially for windows. The tool is called bash after all.

Probably here  https://github.com/sst/opencode/blob/4c261ab1db7ee84770cab21235bb45693b872670/packages/opencode/src/session/system.ts#L41


```ts
const shellName = (process.env.SHELL || process.env.COMSPEC || (process.platform === 'win32' ? 'cmd.exe' : 'sh'))
  .split(/[\\/]/).pop();
...

Platform: ${process.platform}, Shell: ${shellName}
```

But I would not touch this until real windows users have reproducible  issues, as probably Platform is enough

**Comment by rekram1-node** [comment]
Yeah I need to setup a windows environment to test this more and I need to analyze how other tools do it.

the tool name being bash yeah it is confusing for the llm almost certainly 

I think we can addresss that separately tho I want to do more investigation before just changing prompts

**Comment by istarkov** [comment]
I have feeling that at the end it will be running bash in some container env. For reasons like prevent any operation out of project folder etc.

**Comment by rekram1-node** [comment]
@istarkov for those who use things like nunshell or fish, I wonder if this change could actually make their experience worse

We could just also try a check if they have bash installed and use that, but i suppose using the users shell offers some benefits and then it does come back to tool descriptions & names

This looks good, I will merge soon just wanna think more about how we can best serve everyone

**Comment by rekram1-node** [comment]
Given the tool is called bash, almost all unix users have bash, and a lot of windows users have git bash, and the prompts are all about bash, should we just do shell: "bash" if bash is installed? I feel like that's the safest bet here

**Comment by istarkov** [comment]
I have few reasons why current approach is better: 
- 1.  Default bash on mac is outdated and usually need to be changed with `GNU bash`
Default shell on mac - zsh is modern and more compatible with GNU bash vs the default mac bash.
- 2. As a developer I usually check issues with my current terminal and shell, and this is tool for developers ;-)


macOS /bin/bash (3.2) 2007 (18+ years old) ;-)

**Comment by rekram1-node** [comment]
i tend to agree, im just cautious, lemme test something with fish and nushell

**Comment by keathmilligan** [comment]
I suggest it respect SHELL on Windows as well to enable compatibility with Git Bash / MINGW. As it is on Windows, it uses cmd.exe even if you launch from bash. SHELL won't typically be set in cmd/powershell sessions.  Or alternatively, make it configurable.

**Comment by rekram1-node** [comment]
/oc use $SHELL if it is set, otherwise use `shell: true` remove the windows check

**Comment by veracioux** [comment]
Will the LLM know which shell the bash tool will use?

**Comment by rekram1-node** [comment]
nope, but i looked at some other tools and im gonna pass over this and change some things.

I wonder if we should rename the tool to something else tho (thats a later thing tho)

**Comment by Ninja3047** [comment]
This seems like a downgrade for non bash shell users
Maybe it would be better to look for $BASH_SHELL that the user can set or something and then have some logic on MacOS/Windows to look for brew's bash and git bash.
Claude code handles this on windows by requesting the user set a different environment variable to the location of git bash so it doesn't interfere with the user's current shell

**Comment by rekram1-node** [comment]
yeah im doing a pass to fix this I didn't want it to be released already lol

**Comment by rekram1-node** [comment]
@Ninja3047 i was thinking something like this, seems to be similar to how the other coding agents do it:
```
  const shell = iife(() => {
    const s = process.env.SHELL
    if (s) {
      if (!new Set(["/bin/fish", "/bin/nu", "/usr/bin/fish", "/usr/bin/nu"]).has(s)) {
        return s
      }
    }

    if (process.platform === "darwin") {
      return "/bin/zsh"
    }

    if (process.platform === "win32") {
      return "C:\\Windows\\System32\\cmd.exe"
    }

    return true
  })
```

**Comment by Ninja3047** [comment]
Windows should probably default to something more bash compatible since the agent will likely be very confused.

Claude code for example expects you to have git bash and will not work with cmd.exe so checking default git bash install locations might be a better default.

**Comment by rekram1-node** [comment]
Yeah good point, tho I noticed the other tools let u use powershell and stuff so maybe we should just rename the tool or something.

This is a good fix for now tho Ill make it do that

**Comment by veracioux** [comment]
<del>
<p>
@Ninja3047 IMO I don't see any reason to restrict the user not to be able to use whatever shell the user has available. @rekram1-node  I agree that renaming the tool might be a good idea but in any case I think the agent should be informed beforehand what shell the tool is gonna invoke in the end.

I'm talking as a fish user myself.
</p>
</del>

---

Nevermind this makes no sense :D - Aiden's proposed fix is good.

**Comment by Ninja3047** [comment]
Yes but that would require a new prompt and/or tool at least
The bash tool should use bash or something bash compatible (if the user wants to set `BASH_SHELL` to something that isn't bash, I guess they are free to do so at the risk of higher rates of tool calls potentially failing.
Older or smaller models will probably find it difficult to get the syntax for fish correct especially since it's changed a few times over the past couple years so the prompt should probably have some guide to the version of fish being used.

**Comment by rekram1-node** [comment]
I think we do a follow up for that... 

Im just gonna do this for now:
https://github.com/sst/opencode/commit/adf7df0d5c93eba7a430fa55879bbad479bf64ca

Preserves old behavior if u use random shells

**Comment by rekram1-node** [comment]
But I did like what you said about git bash, this does some stuff but maybe we need to search install locations too to be safe
