### PR TITLE
fix(attach): allow remote --dir

### LINKED ISSUE #8981: Bug: attach --dir works incorrectly when using with remote server
### Description

opencode attach --dir does not work correctly when you try to use it with a remote server. It performs client side validation of whether a directory is valid in the context of local machine which breaks when you want to pass that flag to the server.

For instance, from my local machine, you cannot run
opencode attach http://docs:4096 --dir /home/workspace/perry

if my $HOME is different locally.

Proposed minimal fix: https://github.com/anomalyco/opencode/pull/8969

### Plugins

none

### OpenCode version

1.1.24

### Steps to reproduce

Set up remote server over tailnet/somehow accessible

Try to attach with a directory that doesn't exist on the local machine. Example:
opencode attach http://docs:4096 --dir /home/workspace/perry

### Screenshot and/or share link

_No response_

### Operating System

Ubuntu 24.04

### Terminal

Ghostty

### PR DESCRIPTION
**Pull request by gricha**
### What does this PR do?

I spawn OpenCode directly on my dev servers in $HOME. I then try to attach to them from any of my machine, and because projects may be scattered and not at $HOME, I want to be able to use  `--dir` parameter. In these examples `docs` is my hostname in Tailnet.

If I ran `opencode attach docs:4096 --dir ./perry` from my machine earlier, it would consider it a local path and try to push that in. Absolute paths would also be caught with issues like:

ENOENT: no such file or directory, chdir '/home/gricha/personal/opencode-gricha' -> '/home/workspace/perry'

I didn't want to break local-validation functionality you have, so I added gating for local vs. remote attach, and let remote pass through the dir to the upstream server.

### How did you verify your code works?

`opencode attach docs:4096 --dir ./perry`
`opencode attach docs:4096 --dir /home/workspace/perry`
both work properly now - I also tested for whether they are able to load up skills/subagents from those directories after that change and it works fine.

Fixes #8981

### CODE REVIEW

**Comment by gricha** [comment]
I'd not consider this a duplicate, I think this is a much simpler fix of existing functionality that just makes sure that intended behavior works properly.

File: packages/opencode/src/cli/cmd/tui/attach.ts [hunk 1]
```diff
@@ -1,6 +1,18 @@
...
+
+function resolveDir(url: string, dir?: string) {
+  if (!dir) return dir
+  const target = URL.canParse(url) ? new URL(url) : new URL(`http://${url}`)
+  if (!localHosts.has(target.hostname)) return dir
+  if (path.isAbsolute(dir)) return dir
+  const base = process.env.PWD ?? process.cwd()
+  return path.resolve(base, dir)
+}
+
```
Comment (gricha) [inline packages/opencode/src/cli/cmd/tui/attach.ts]: thinking about this a little bit more I don't think I like this whole resolution, it makes assumptions on what's local vs. remote, doesn't consider ipv6 and could cause problems, and I think the biggewst issue is with process.chdir check

File: packages/opencode/src/cli/cmd/tui/attach.ts [hunk 2]
```diff
@@ -21,11 +33,10 @@ export const AttachCommand = cmd({
         describe: "session id to continue",
       }),
   handler: async (args) => {
-    if (args.dir) process.chdir(args.dir)
```
Comment (gricha) [inline packages/opencode/src/cli/cmd/tui/attach.ts]: So this is what currently trips up the process if I pass dir to attach. It absolutely works fine without it if I just drop this attempt, but I am not sure what consequences it can have for the local development.

@rekram1-node @thdxr would the version be ok where I either remove just this line OR make it best effort and silently fail it? That would solve issue with passing --dir to remote server as well.

Comment (rekram1-node) [reply packages/opencode/src/cli/cmd/tui/attach.ts]: believe so

Comment (gricha) [reply packages/opencode/src/cli/cmd/tui/attach.ts]: ok, changed the logic - if we *can* chdir, we do, and set directory to CWD. if we can't we just blank pass dir through. Let me know if that's good

Comment (gricha) [reply packages/opencode/src/cli/cmd/tui/attach.ts]: @rekram1-node Sorry to bug you, I know y'all are swamped in PRs. I think I fixed this to be minimal, targeted fix.

**Comment by gricha** [comment]
@rekram1-node @thdxr could I get a quick look at this? i spin up one server remotely on my docker containers right now, and having this validation disabled would let me start them in the right repositories, with proper skills/agents loaded up. I have to do a bit of a dance right now without it. sorry to bug multiple times about that
