### PR TITLE
fix: Enable Windows builds and fix bun+pnpm install on Windows

### LINKED ISSUE #3363: make `bun install` work on Windows
Currently, we are able to install opencode on Windows via `npm install -g opencode-ai`. But trying to install opencode via bun (`bun install -g opencode-ai`) and then running opencode results in the following error - 

```sh
error: interpreter executable "/bin/sh" not found in %PATH%

Bun failed to remap this bin to its proper location within node_modules.
This is an indication of a corrupted node_modules directory.
```

This is probably due to how the current `npm install` script works by rebuilding the binary shims on Windows

### LINKED ISSUE #4195: windows version installed from pnpm does not work
### Description

on cmd:

```
>opencode
The system cannot find the path specified.
```

on git bash:

```
$ opencode
It seems that your package manager failed to install the right version of the opencode CLI for your platform. You can try manually installing the "opencode-win32-x64" package
```

on pwsh:

```
> opencode
&: C:\Users\bians\AppData\Local\pnpm\opencode.ps1:36
Line |
  36 |      & "/bin/sh$exe"  "$basedir/global/5/.pnpm/opencode-ai@1.0.55/node …
     |        ~~~~~~~~~~~~~
     | The term '/bin/sh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

it seemed to be seeking for sth like "/bin/sh" and failed, but it does not work with git bash either.

### OpenCode version

1.0.55

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

windows 11 x64

### Terminal

windows terminal

### PR DESCRIPTION
**Pull request by Hona**
Fixes #3363 - `bun install -g opencode-ai` now works on Windows
Fixes #4195 - `pnpm install -g opencode-ai` now works on Windows

  ### Problem
  OpenCode could not be built or installed on Windows using bun due to three critical issues:

  1. **Build script platform mismatch**: The build script used `"windows"` as the platform identifier, but `process.platform` returns `"win32"` on Windows. This caused:
     - The `--single` flag to fail (built wrong platform or nothing at all)
     - Package names like `opencode-windows-x64` that didn't match the expected `opencode-win32-x64`

  2. **Windows path separator bug**: The build script used `path.relative()` which returns backslashes on Windows (`\`), but the bundled code expected forward slashes (`/`). This
  caused syntax errors and made all Windows builds fail.

  3. **Bun install failure**: The postinstall script skipped all processing when detecting bun on Windows, causing bun to generate a default `#!/bin/sh` wrapper script that failed
  with:
     error: interpreter executable "/bin/sh" not found in %PATH%

  ### Solution

  #### 1. Platform naming consistency
  - Changed platform identifier from `"windows"` to `"win32"` in:
    - `build.ts`: Target definitions and package.json generation
    - `postinstall.mjs`: Platform detection logic
  - This ensures consistency with Node.js's `process.platform` value

> [!WARNING]
> I'm not sure how this would interact with old installs -> upgrade paths 

  #### 2. Path separator normalization
  - Added `.replace(/\\/g, "/")` to normalize Windows backslashes to forward slashes in bundled paths
  - Fixes the `OTUI_TREE_SITTER_WORKER_PATH` define that was causing build failures

  #### 3. Bun support on Windows
  - Added explicit bun detection and handling in `postinstall.mjs`
  - For bun on Windows: copies the `.exe` directly to the bin directory (bun doesn't need wrapper scripts)
  - For npm on Windows: continues to use `npm rebuild` to regenerate CMD/PS1 wrappers
  - For other package managers on Windows: gracefully skips with a clear message

  ### Testing

  Verified the following scenarios work correctly:

  - ✅ `bun run script/build.ts --single` on Windows (now builds `opencode-win32-x64`)
  - ✅ Full build on Windows without errors
  - ✅ `bun install -g opencode-ai` on Windows (no more `/bin/sh` error)
  - ✅ `npm install -g opencode-ai` on Windows (CMD wrappers still generated correctly)
  - ✅ Postinstall script correctly detects and handles npm vs bun on Windows

### CODE REVIEW

File: packages/opencode/script/postinstall.mjs [hunk 1]
```diff
@@ -102,27 +143,37 @@ async function main() {
...
+        copyBinary(binaryPath, binaryName)
+        return
+      }
 
-    // Remove existing bin script if it exists
-    if (fs.existsSync(binScript)) {
-      fs.unlinkSync(binScript)
+      // Unknown package manager on Windows
+      console.log("Windows detected but unknown package manager, skipping postinstall")
+      return
```
Comment (rekram1-node) [inline packages/opencode/script/postinstall.mjs:170]: Is this return necessary? It does change the pre-existing behavior, like what would happen if someone tried yarn?

NOTE: i have never used yarn so maybe it has behaviors im unaware of

Comment (Hona) [reply packages/opencode/script/postinstall.mjs:170]: Yeah return here is a no op, I'll remove it.

Previously unknown package managers printed 'Windows detected but not npm, skipping postinstall' and did nothing. This keeps it the same. We can best guess a binary copy or leave as is

Comment (rekram1-node) [reply packages/opencode/script/postinstall.mjs:170]: oh nvm i think this isn't an issue actually
