### PR TITLE
fix(task): respect agent permission config for todowrite tool

### LINKED ISSUE #19101: `todowrite`/`todoread` cannot be enabled for subagents via agent `permission` config
### Description

The documentation states that `todowrite` and `todoread` are "disabled for subagents by default, but you can enable it manually" via the agent's `permission` field. However, setting `todowrite: allow` and `todoread: allow` in a custom subagent's permission config has no effect — the tools remain unavailable at runtime.

### Steps to Reproduce

1. Create a custom subagent markdown file (e.g., `~/.config/opencode/agents/executor.md`):

```markdown
---
description: Executes markdown plans iteratively
mode: subagent
permission:
  edit: deny
  bash:
    "*": deny
  task:
    "*": deny
    "build": allow
  webfetch: deny
  todowrite: allow
  todoread: allow
---

You are a plan executor agent. Use todowrite and todoread to track tasks.
```

2. Invoke the agent via `@executor` or have a primary agent delegate to it via the Task tool.
3. The agent attempts to call `todowrite`.

### Expected Behavior

The `todowrite` and `todoread` tools should be available to the subagent, as configured in the agent's `permission` block.

### Actual Behavior

```
⚙ invalid [tool=todowrite, error=Model tried to call unavailable tool 'todowrite'. Available tools: invalid, read, glob, grep, task, skill.]
```

### Root Cause

The Task tool implementation in `packages/opencode/src/tool/task.ts` hardcodes `todowrite` and `todoread` as denied in two places, overriding the agent's permission config:

**1. Session creation** — hardcoded deny permissions on the child session:

```typescript
return await Session.create({
  // ...
  permission: [
    { permission: "todowrite", pattern: "*", action: "deny" },
    { permission: "todoread",  pattern: "*", action: "deny" },
    // ...
  ],
})
```

**2. `SessionPrompt.prompt` call** — hardcoded `false` in the tools object:

```typescript
const result = await SessionPrompt.prompt({
  // ...
  tools: {
    todowrite: false,
    todoread: false,
    // ...
  },
})
```

In `prompt.ts`, the deprecated `tools` parameter is converted to session-level permissions and applied via `Session.setPermission`, which overwrites the session permissions set during creation. Since `Permission.merge(agent.permission, session.permission)` is used at evaluation time, the session-level deny always wins over the agent-level allow.

There is an existing pattern for conditionally skipping this override — the `task` permission uses a `hasTaskPermission` check:

```typescript
const hasTaskPermission = agent.permission.some((rule) => rule.permission === "task")

// ...
permission: [
  // ...
  ...(hasTaskPermission
    ? []
    : [{ permission: "task", pattern: "*", action: "deny" }]),
],
```

But no equivalent check exists for `todowrite`/`todoread`.

### Suggested Fix

Add a similar check for `todowrite` and `todoread` that respects the agent's permission config:

```typescript
const hasTodoWritePermission = agent.permission.some(
  (rule) => rule.permission === "todowrite" && rule.action === "allow"
)
const hasTodoReadPermission = agent.permission.some(
  (rule) => rule.permission === "todoread" && rule.action === "allow"
)
```

Then conditionally include the deny rules in session creation:

```typescript
permission: [
  ...(hasTodoWritePermission
    ? []
    : [{ permission: "todowrite", pattern: "*", action: "deny" }]),
  ...(hasTodoReadPermission
    ? []
    : [{ permission: "todoread", pattern: "*", action: "deny" }]),
  // ...
],
```

And similarly for the `tools` object passed to `SessionPrompt.prompt`:

```typescript
tools: {
  todowrite: hasTodoWritePermission ? undefined : false,
  todoread: hasTodoReadPermission ? undefined : false,
  // ...
},
```

### Environment

- OpenCode version: latest (dev branch as of 2025-03-25)
- OS: Linux
- Relevant files: `packages/opencode/src/tool/task.ts`, `packages/opencode/src/session/prompt.ts`

### Plugins

no plugins

### OpenCode version

1.3.0

### Steps to reproduce

1. Create a custom subagent markdown file (e.g., `~/.config/opencode/agents/executor.md`):

```markdown
---
description: Executes markdown plans iteratively
mode: subagent
permission:
  edit: deny
  bash:
    "*": deny
  task:
    "*": deny
    "build": allow
  webfetch: deny
  todowrite: allow
  todoread: allow
---

You are a plan executor agent. Use todowrite and todoread to track tasks.
```

2. Invoke the agent via `@executor` or have a primary agent delegate to it via the Task tool.
3. The agent attempts to call `todowrite`.

### Screenshot and/or share link

_No response_

### Operating System

Ubuntu 25.10

### Terminal

Alacritty

### PR DESCRIPTION
**Pull request by ariane-emory**
### Issue for this PR

Closes anomalyco#19101

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

The todowrite tool was hardcoded as denied for all subagents, preventing users from enabling them via agent permission configuration even when explicitly allowed.

This change follows the existing pattern used for the task permission by checking if the agent has explicit allow rules for the todowrite tool before applying the default deny.

Changes:
- Add hasTodoWritePermission check
- Conditionally include deny rules in session creation
- Conditionally include false values in tools object

### How did you verify your code works?

Manual A/B testing, `bun test`, `bun typecheck`.

### Screenshots / recordings

No UI changes.

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### CODE REVIEW

File: packages/opencode/src/tool/task.ts [hunk 1]
```diff
@@ -64,6 +64,7 @@ export const TaskTool = Tool.define("task", async (ctx) => {
       if (!agent) throw new Error(`Unknown agent type: ${params.subagent_type} is not a valid agent type`)
 
       const hasTaskPermission = agent.permission.some((rule) => rule.permission === "task")
+      const hasTodoWritePermission = agent.permission.some((rule) => rule.permission === "todowrite" && rule.action === "allow")
```
Comment (dbpolito) [inline packages/opencode/src/tool/task.ts]: do we really want check allow here? because if the agent added ask, it should be respected, right? right now you will still deny it...

maybe keep consistent with the task check just checking if there agent is changing the permission

Comment (ariane-emory) [reply packages/opencode/src/tool/task.ts]: Adding "ask" in a (non-interactive) _subagent_ session would likely have undesirable results if respected.

Comment (ariane-emory) [reply packages/opencode/src/tool/task.ts]: Changed as per your suggestion on Discord.
