### PR TITLE
fix(agent): default agent selection in acp and headless mode

### LINKED ISSUE #8680: ACP and headless mode does not respect default agent definition
### Description

The `defaultAgent()` function does not properly filter agents by their mode and visibility settings. This causes subagents (like `explore`) and hidden agents (like `compaction`) to be incorrectly selected as the default agent in ACP and headless (`run`) modes.

**Root causes:**
1. `Agent.defaultAgent()` returns the first agent from `state()` without checking if it's a subagent or hidden
2. ACP session init does not persist the resolved default mode, causing `prompt()` to use stale/wrong mode

### Plugins

N/A

### OpenCode version

0.0.0-dev-202601151329

### Steps to reproduce

fresh config -> disable build agent -> set a custom default agent -> execute opencode run "echo back" -> it uses plan agent and tries to generate a plan

example jsonc config:

```jsonc
{
  "$schema": "https://opencode.ai/config.json",
  "default_agent": "yoda",
  "agent": {
    "build": {
      "disable": true,
    },
    "yoda": {
      "prompt": "say YODA! before every response.",
    },
  },
}
```

#### opencode run 

current version output:

```sh
$ opencode run "echo back"
|  Write    .opencode/plans/1768489599174-witty-cabin.md
```

fixed version output:

```sh
$ bun run dev run "echo back"

YODA!
echo back
```

#### opencode acp

```typescript
// acp-run.ts
import { spawn } from "bun"

const prompt = process.argv[3] || "echo back"

const testVersion = process.argv.find((arg) => arg.startsWith("--test-version="))?.split("=")[1] || "fixed"
console.log(`Using ACP version: ${testVersion}`)
const acpCommand =
  testVersion === "current"
    ? ["opencode", "acp"]
    : ["bun", "run", "--cwd", "./packages/opencode/", "--conditions=browser", "src/index.ts", "acp"]

const acp = spawn(acpCommand, {
  stdin: "pipe",
  stdout: "pipe",
  stderr: "ignore",
})

const send = (msg: object) => acp.stdin.write(JSON.stringify(msg) + "\n")

let id = 0
const rpc = (method: string, params: object) => send({ jsonrpc: "2.0", id: ++id, method, params })

// Initialize
rpc("initialize", { protocolVersion: 1, clientCapabilities: {} })

// Create session
rpc("session/new", { cwd: process.cwd(), mcpServers: [] })

// Read responses
const reader = acp.stdout.getReader()
const decoder = new TextDecoder()
let buffer = ""
let sessionId = ""

while (true) {
  const { done, value } = await reader.read()
  if (done) break

  buffer += decoder.decode(value)
  const lines = buffer.split("\n")
  buffer = lines.pop() || ""

  for (const line of lines) {
    if (!line) continue
    const msg = JSON.parse(line)

    // Get session ID from session/new response
    if (msg.result?.sessionId) {
      sessionId = msg.result.sessionId
      rpc("session/prompt", { sessionId, prompt: [{ type: "text", text: prompt }] })
    }

    // Print agent message chunks
    if (msg.params?.update?.sessionUpdate === "agent_message_chunk") {
      process.stdout.write(msg.params.update.content.text || "")
    }

    // Exit on completion
    if (msg.result?.stopReason === "end_turn") {
      console.log()
      process.exit(0)
    }
  }
}
```

In the project root, checked out to the fix branch in [fix(agent): default agent selection in acp and headless modes #8678](https://github.com/anomalyco/opencode/pull/8678), execute this script in two different modes:

current opencode version, as-is:

```sh
[/path/to/opencode/fix-default-agent-selection]
$ bun acp-run.ts --test-version=current
Using ACP version: current

I'll help you understand the codebase and create a plan. Let me start by exploring the repository structure to understand what we're working with.

I'll help you understand the overall structure of this codebase. Let me start by exploring the repository structure and key files.

Now let me explore the main packages directory to understand the architecture:

...
```

fixed version:

```sh
[/path/to/opencode/fix-default-agent-selection]
$ bun acp-run.ts --test-version=fixed
Using ACP version: fixed

YODA! echo back%
```

### Screenshot and/or share link

N/A

### Operating System

macOS Tahoe 26.3 arm64

### Terminal

ghostty 1.2.3
tmux next-3.5

### PR DESCRIPTION
**Pull request by assagman**
## Summary
Make ACP and headless mode respect `default_agent` config and properly handle agent modes and visibilities. Previously, subagents and hidden agents could be incorrectly selected as the default agent.

Fixes #8680

## Changes
- Filter out subagents (`mode === "subagent"`) from defaultAgent candidates
- Filter out hidden agents (`hidden === true`) from defaultAgent candidates
- 4 different errors introduced:
  - `default agent "${cfg.default_agent}" not found`
  - `default agent "${cfg.default_agent}" is a subagent`
  - `default agent "${cfg.default_agent}" is hidden`
  - `no primary visible agent found`
- Add 7 test cases for defaultAgent selection logic
- Persist default mode in session manager during ACP session init

## Breaking Changes
None

## Testing
- Added unit tests covering agent selection cases

### CODE REVIEW

File: packages/opencode/src/agent/agent.ts [hunk 1]
```diff
@@ -255,7 +255,9 @@ export namespace Agent {
   }
 
   export async function defaultAgent() {
-    return state().then((x) => Object.keys(x)[0])
+    const agents = await list()
+    const primaryVisible = agents.find((a) => a.mode !== "subagent" && a.hidden !== true)
+    return primaryVisible?.name || "build"
```
Comment (rekram1-node) [inline packages/opencode/src/agent/agent.ts]: I think we should prolly throw an error if no primary agent is available... Thoughts?

Comment (assagman) [reply packages/opencode/src/agent/agent.ts]: Yes, I'm currently thinking about it. Maybe you're right.

TUI throws unhandled exception here:  https://github.com/anomalyco/opencode/blob/dev/packages/opencode/src/cli/cmd/tui/context/local.tsx#L41-L41 

(when no primary visible agent found)

Comment (assagman) [reply packages/opencode/src/agent/agent.ts]: Hey @rekram1-node , I've updated the logic as throwing errors for invalid cases:

1. cfg.default_agent is set:
  a. cfg.default_agent is not found in state
  b. cfg.default_agent is a subagent
  c. cfg.default_agent is hidden
4. cfg.default_agent is not set and all of them either subagent or hidden -> no primary visible agent found
