### PR TITLE
fix: `rg` hanging forever when run in bash, waiting for stdin

### LINKED ISSUE #3089: `rg` hangs indefinitely in 0.14.7 in a linux/amd64 container; works on 0.14.6
I think something about 0.14.7 broke the shell with ripgrep.   The command times out and doesn't display output.  Things are swimming on 0.14.6.

### PR DESCRIPTION
**Pull request by remorses**
Pass ignore to stdin so that rg does not wait for stdin input. This probably fixes other commands hanging

Fix https://github.com/sst/opencode/issues/3089

### CODE REVIEW

File: packages/opencode/src/tool/bash.ts [hunk 1]
```diff
@@ -146,9 +145,11 @@ export const BashTool = Tool.define("bash", {
       })
     }
 
-    const process = exec(params.command, {
+    const process = spawn(params.command, {
+      shell: 'bash',
```
Comment (rekram1-node) [inline packages/opencode/src/tool/bash.ts]: will this break windows?

Comment (remorses) [reply packages/opencode/src/tool/bash.ts]: It will work if the user has bash in PATH 

I know Git for windows also installs Git Bash so we should use that if the user hasn't bash in path

This is what Claude Code does: if there is no global bash in Windows try to use C:\Program Files\Git\bin\bash.exe or the env variable CLAUDE_CODE_GIT_BASH_PATH

This should be done in a separate PR

Comment (rekram1-node) [reply packages/opencode/src/tool/bash.ts]: I think leaving it with just `shell: true` makes sense for now to avoid any breaking changes

Comment (rekram1-node) [reply packages/opencode/src/tool/bash.ts]: it preserves existing behavior and fixes issue

**Comment by jscheel** [comment]
This is still an issue. File references cause opencode to use 100% of a core indefinitely, and the search will never return a result. Ripgrep work fine when run from the shell.

**Comment by rekram1-node** [comment]
That one is slightly different but we will check it out thank you for raising

**Comment by rekram1-node** [comment]
@jscheel can you confirm that you aren't working in a python project and that ripgrep is the actual issue?

Because I have seen some issues like that specifically for python projects due to the lsp server

**Comment by jscheel** [comment]
Ah, definitely a Python project. Was assuming rg based on previous discord
conversations 😅

**Comment by rekram1-node** [comment]
@jscheel to fix this add the following to your opencode.json (long term we need to fix something but for short term usability this may be good):
```
{
  "lsp": {
     "pyright": {
         "disabled": true
      }
  }
}

**Comment by jscheel** [comment]
@rekram1-node 🫡 will give it a try. Thanks! I can help debug anything if necessary.

**Comment by remorses** [comment]
@rekram1-node  let's just disable LSP by default. It causes so many opencode issues and it must already have churned so many users. I am able to use opencode just because I disabled it

**Comment by rekram1-node** [comment]
@remorses hm ultimately the decision isn't up to me but at my previous job I literally couldn't get an agent to write good java  (in sufficiently large codebase) without the lsp feedback it would always have some error 

but I get what your point is I saw the change my mind in discord too haha

**Comment by jscheel** [comment]
The lsp is incredibly valuable. I’m not sure the answer is to just disable
it. Do we know what the issue is that causes it to hang in Python so badly?

**Comment by rekram1-node** [comment]
@jscheel if you try the latest version this has been fixed, you should be able to remove that disable now

**Comment by jscheel** [comment]
@rekram1-node hah, love it. Bumping to 0.15.1 now, will give it a run.
