### PR TITLE
fix: publish session.error event for invalid model selection

### LINKED ISSUE #8460: API doesn't report invalid model errors via event stream
### Description

# API doesn't report invalid model errors via event stream

## Bug

When sending a message via the API with an invalid provider/model ID, no error is surfaced to the client. The session silently goes from `busy` to `idle` with no indication that anything went wrong.

## Reproduction

1. Start opencode server
2. Listen to events: `curl http://localhost:4096/event`
3. Send a message with an invalid provider:
   ```bash
   curl -X POST http://localhost:4096/session/{sessionID}/message \
     -H "Content-Type: application/json" \
     -d '{"model": {"providerID": "invalid", "modelID": "some-model"}, "parts": [{"type": "text", "text": "hello"}]}'
   ```
4. Observe: HTTP 200, session goes busy → idle, no `session.error` event

## Expected

A `session.error` event should be published with a message like "Model not found: invalid/some-model. Did you mean: ...?"

## Cause

`Provider.getModel()` is called inside `loop()` after the HTTP response has already started streaming. The error is thrown but never converted to a `session.error` event.

### Plugins

_No response_

### OpenCode version

_No response_

### Steps to reproduce

_No response_

### Screenshot and/or share link

_No response_

### Operating System

_No response_

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by surma**
# Fix: Publish session.error event for invalid model selection

## Problem

When sending a message via the API with an invalid provider or model ID, the error was silently swallowed. API consumers had no way to know something went wrong.

**What happened:**

1. POST to `/session/{id}/message` with `{ model: { providerID: "invalid", ... } }`
2. HTTP response returns 200 immediately (before validation)
3. User message is created successfully
4. Session goes `busy` → `idle` with no error indication
5. No `session.error` event is published to `/event`

**Root cause:** The `Provider.getModel()` call happens inside `loop()` after the HTTP response has already started streaming. When it throws `ModelNotFoundError`, the error propagates up but is never converted to a `session.error` event.

## Solution

Added error handling around `Provider.getModel()` in `loop()` to publish a `session.error` event before re-throwing. This matches the existing pattern used in the `command()` function.

**After this fix:**

```
data: {"type":"session.error","properties":{"sessionID":"ses_...","error":{"name":"UnknownError","data":{"message":"Model not found: invalid/some-model. Did you mean: anthropic, openai, ...?"}}}}
```

## Changes

- `packages/opencode/src/session/prompt.ts`: Wrap `Provider.getModel()` in try-catch, publish `session.error` on `ModelNotFoundError`

Fixes #8460

### CODE REVIEW

File: packages/opencode/src/session/prompt.ts [hunk 1]
```diff
@@ -309,7 +309,20 @@ export namespace SessionPrompt {
...
         })
 
-      const model = await Provider.getModel(lastUser.model.providerID, lastUser.model.modelID)
+      let model: Provider.Model
+      try {
+        model = await Provider.getModel(lastUser.model.providerID, lastUser.model.modelID)
+      } catch (e) {
+        if (Provider.ModelNotFoundError.isInstance(e)) {
+          const { providerID, modelID, suggestions } = e.data
+          const hint = suggestions?.length ? ` Did you mean: ${suggestions.join(", ")}?` : ""
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: prefer .catch see style guide
