### PR TITLE
fix(tui): restore showDetails check removed in Permission rework

### LINKED ISSUE #7286: regression: tool_details / "Hide tool details" no longer working.
### Description

The command pallete contains an item titled "Hide show details". This allowed the user to hide tool calls and their output from the session view. 

This seems to be no longer working and appears to have been broken approximately two or three days ago.

### Plugins

None

### OpenCode version

1.1.6

### Steps to reproduce

1. Attempt to use the "Hide tool details" item in the command palette (or strike a key that is bound to `tool_details`.
2. Observe that nothing happens and tool calls/output remains visible.

### Screenshot and/or share link

_No response_

### Operating System

MacOS Sequoia latest

### Terminal

iTerm2

### PR DESCRIPTION
**Pull request by ryangamerdev**
Fixes #7286

## Problem

The 'Hide tool details' toggle in the command palette (Ctrl+P) has no effect on the UI - completed tools are always displayed regardless of the setting.

## Root Cause

The Permission rework commit 351ddeed9 (merged 2026-01-01, PR #6319) accidentally removed the `showDetails` check from the `ToolPart` function when refactoring the tool rendering system.

### Before Permission rework (working):

```typescript
function ToolPart(props: { last: boolean; part: ToolPart; message: AssistantMessage }) {
  const { theme } = useTheme()
  const { showDetails } = use()  // <-- Gets showDetails from context
  const sync = useSync()
  const [margin, setMargin] = createSignal(0)
  const component = createMemo(() => {
    // Hide tool if showDetails is false and tool completed successfully
    // But always show if there's an error or permission is required
    const shouldHide =
      !showDetails() &&
      props.part.state.status === "completed" &&
      !sync.data.permission[props.message.sessionID]?.some((x) => x.callID === props.part.callID)

    if (shouldHide) {
      return undefined  // <-- Returns nothing, hiding the tool
    }
    // ...
  })
}
```

### After Permission rework (broken):

```typescript
function ToolPart(props: { last: boolean; part: ToolPart; message: AssistantMessage }) {
  const sync = useSync()
  // <-- No use() call!
  // <-- No showDetails check!

  const toolprops = { /* ... */ }

  return (
    <Switch>
      // <-- Always renders all tools unconditionally
    </Switch>
  )
}
```

## Fix

Restore the showDetails check by:
1. Adding `const ctx = use()` to access the context
2. Adding a `shouldHide` memo with the original logic
3. Wrapping the return in `<Show when={!shouldHide()}>`

The fix preserves the original behavior:
- Hide completed tools when showDetails is false
- Always show tools that are pending/running (so users see progress)
- Always show tools that require permission (so users can respond)

The fix uses the same permission data structure (`x.tool?.callID`) as the existing code, aligning with the new permission system introduced in the rework.

### CODE REVIEW

File: packages/opencode/src/cli/cmd/tui/routes/session/index.tsx [hunk 1]
```diff
@@ -1324,8 +1324,19 @@ function TextPart(props: { last: boolean; part: TextPart; message: AssistantMess
...
 
+  // Hide tool if showDetails is false and tool completed successfully
+  // But always show if there's an error or permission is required
+  const shouldHide = createMemo(() => {
+    if (ctx.showDetails()) return false
+    if (props.part.state.status !== "completed") return false
+    const permissions = sync.data.permission[props.message.sessionID] ?? []
+    if (permissions.some((x) => x.tool?.callID === props.part.callID)) return false
+    return true
+  })
```
Comment (rekram1-node) [inline packages/opencode/src/cli/cmd/tui/routes/session/index.tsx:1335]: Wait i dont think this part makes sense anymore w/ new dialog changes for permissions

Comment (ryangamerdev) [reply packages/opencode/src/cli/cmd/tui/routes/session/index.tsx:1335]: You're right.  Updated and pushed.

**Comment by ariane-emory** [comment]
This does seem like it works to me. Fingers crossed that we'll see it merged soon - I (and probably others, I'd guess) do frequently use this feature, so I'd love to see its functionality restored.
