### PR TITLE
fix(opencode): pass missing auth headers in `run --attach`

### LINKED ISSUE #16096: `opencode run --attach` ignores OPENCODE_SERVER_PASSWORD
### Description

When using `opencode run --attach=localhost:<port>` with
  `OPENCODE_SERVER_USERNAME` and `OPENCODE_SERVER_PASSWORD` env vars, the
  command fails with "Error: Session not found".

  The `run` command in `packages/opencode/src/cli/cmd/run.ts` (~line 650) does
   not pass auth headers to `createOpencodeClient`:

  ```typescript
  if (args.attach) {
    const sdk = createOpencodeClient({ baseUrl: args.attach, directory })
    // No auth headers passed!
    return await execute(sdk)
  }
```

  The `attach` TUI command correctly builds `Basic` auth headers from the env vars
   (in `packages/opencode/src/cli/cmd/tui/attach.ts`), but `run` does not.

### Plugins

_No response_

### OpenCode version

1.2.17

### Steps to reproduce

1. Start a server with auth: `OPENCODE_SERVER_PASSWORD=secret opencode serve
  --port 4096`
2. Run: `OPENCODE_SERVER_USERNAME=opencode OPENCODE_SERVER_PASSWORD=secret  opencode --attach=localhost:4096 run hello`
3. Get: `Error: Session not found`
4. Compare with `opencode attach localhost:4096 -p secret` which works fine
  because attach.ts passes auth headers to the SDK client.

### Screenshot and/or share link

_No response_

### Operating System

macOS 15.5

### Terminal

Ghostty, zsh, cmux

### PR DESCRIPTION
**Pull request by ericclemmons**
### Issue for this PR

Closes #16096 

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

Adds missing Basic auth headers to `run` command, just like `attach`.

### How did you verify your code works?

Relied on tests (that I've since removed to be consistent with the other patterns) and comparing `run` against `opencode serve` vs. one with Basic auth (like what `OpenCode.app` starts):

1. ✅ `opencode --attach http://127.0.0.1:45103 --dir ~/workspace run howdy`
2. ❌ `OPENCODE_SERVER_USERNAME=opencode OPENCODE_SERVER_PASSWORD=hunter2 opencode --attach=localhost:4096 run howdy`
  
    > Error: Session not found

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### Notes

I originally started refactoring out a `getAuthorizationHeader` utility based on https://github.com/anomalyco/opencode/blob/85ff05670a53079066fcbc0abc0271ea355585c1/packages/opencode/src/cli/cmd/tui/worker.ts#L147, but opted for inlining & duplicating what was in https://github.com/anomalyco/opencode/blob/85ff05670a53079066fcbc0abc0271ea355585c1/packages/opencode/src/cli/cmd/tui/attach.ts#L63-L68

I **did** use AI to author this because I was in the middle of another project when I finally asked Claude "Wait, is this an opencode bug??" and wound up here.

I'm sorry. 😔

### CODE REVIEW

File: packages/opencode/src/cli/cmd/run.ts [hunk 1]
```diff
@@ -280,6 +280,11 @@ export const RunCommand = cmd({
         type: "string",
         describe: "attach to a running opencode server (e.g., http://localhost:4096)",
       })
+      .option("password", {
+        alias: ["p"],
+        type: "string",
+        describe: "basic auth password (defaults to OPENCODE_SERVER_PASSWORD)",
+      })
```
Comment (ericclemmons) [inline packages/opencode/src/cli/cmd/run.ts:287]: So that we're consistent with `attach`:
https://github.com/anomalyco/opencode/blob/85ff05670a53079066fcbc0abc0271ea355585c1/packages/opencode/src/cli/cmd/tui/attach.ts#L37-L41

File: packages/opencode/src/cli/cmd/run.ts [hunk 2]
```diff
@@ -648,7 +653,13 @@ export const RunCommand = cmd({
     }
 
     if (args.attach) {
-      const sdk = createOpencodeClient({ baseUrl: args.attach, directory })
+      const headers = (() => {
+        const password = args.password ?? process.env.OPENCODE_SERVER_PASSWORD
+        if (!password) return undefined
+        const auth = `Basic ${Buffer.from(`opencode:${password}`).toString("base64")}`
+        return { Authorization: auth }
+      })()
```
Comment (ericclemmons) [inline packages/opencode/src/cli/cmd/run.ts:662]: This is modeled after https://github.com/anomalyco/opencode/blob/85ff05670a53079066fcbc0abc0271ea355585c1/packages/opencode/src/cli/cmd/tui/attach.ts#L63-L68

File: packages/opencode/src/cli/cmd/run.ts [hunk 3]
```diff
@@ -648,7 +653,13 @@ export const RunCommand = cmd({
     }
 
     if (args.attach) {
-      const sdk = createOpencodeClient({ baseUrl: args.attach, directory })
+      const headers = (() => {
+        const password = args.password ?? process.env.OPENCODE_SERVER_PASSWORD
```
Comment (nexxeln) [inline packages/opencode/src/cli/cmd/run.ts:657]: This still hardcodes "opencode", so run --attach will keep failing against servers using a non-default OPENCODE_SERVER_USERNAME. Can we read the username from env here (like worker.ts) instead of only fixing the password path?

**Review by nexxeln — CHANGES_REQUESTED** [review]

File: packages/opencode/src/cli/cmd/run.ts (hunk 3 above)
Comment (ericclemmons) [reply packages/opencode/src/cli/cmd/run.ts:657]: Yessir! This was my mistake in the "cleanup".  I originally pulled this utility out for re-use, but felt it was too large:

https://github.com/anomalyco/opencode/blob/85ff05670a53079066fcbc0abc0271ea355585c1/packages/opencode/src/cli/cmd/tui/worker.ts#L147-L152

Comment (ericclemmons) [reply packages/opencode/src/cli/cmd/run.ts:657]: Resolved in a683880a5

**Review by nexxeln — APPROVED** [review]
