### PR TITLE
fix(app): open in powershell

### LINKED ISSUE #15111: bug(desktop): open in powershell does not work
### Description

open in powershell does not work 

### Plugins

null

### OpenCode version

latest

### Steps to reproduce

1. open desktop app
2. try opening project in powershell

### Screenshot and/or share link

_No response_

### Operating System

windows

### Terminal

_No response_

### PR DESCRIPTION
**Pull request by neriousy**
### Issue for this PR

Closes #15111 

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

fixes the path when trying open current project in powershell

**If you paste a large clearly AI generated description here your PR may be IGNORED or CLOSED!**

### How did you verify your code works?

run desktop app on windows and try opening project in powershell

### Screenshots / recordings

https://github.com/user-attachments/assets/2f17dfb0-6697-4345-ba5b-57f629e6c55b

_If this is a UI change, please include a screenshot or recording._

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

_If you do not follow this template your PR will be automatically rejected._

### CODE REVIEW

File: packages/desktop/src-tauri/src/os/windows.rs [hunk 1]
```diff
@@ -7,8 +7,8 @@ use std::{
 use windows_sys::Win32::{
     Foundation::ERROR_SUCCESS,
     System::Registry::{
-        HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE, REG_EXPAND_SZ, REG_SZ, RRF_RT_REG_EXPAND_SZ,
-        RRF_RT_REG_SZ, RegGetValueW,
+        RegGetValueW, HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE, REG_EXPAND_SZ, REG_SZ,
+        RRF_RT_REG_EXPAND_SZ, RRF_RT_REG_SZ,
```
Comment (neriousy) [inline packages/desktop/src-tauri/src/os/windows.rs]: 5.3 said i want it grouped nicely - i didn't argue
