### PR TITLE
fix: add doom loop detection

### LINKED ISSUE #3444: GLM-4.6 model gets stuck in infinite loop, repeating same actions
When using the GLM-4.6 model with opencode, the agent sometimes gets stuck in an infinite loop where it performs the same actions repeatedly instead of progressing through the task. This behavior doesn't occur with Claude Code or other models.

## Steps to reproduce:
1. Use opencode with GLM-4.6 model (via z.ai plan provider)
2. Give a moderately complex task that requires multiple steps
3. Observe that the agent starts repeating the same tool calls or actions
4. The agent continues this loop indefinitely without completing the task

## Expected behavior:
The agent should progress through the task logically, completing each step and moving to the next one, similar to how Claude Code behaves.

## Actual behavior:
The GLM-4.6 model gets stuck repeating the same actions in a loop, never progressing to complete the task.

## Environment:
- Model: GLM-4.6 (z.ai plan provider)
- Other models work fine (Claude Code, etc.)

## Additional context:
This appears to be specific to the GLM-4.6 model's behavior or how it processes the opencode tool system. The issue doesn't occur with other models, suggesting it's not a general opencode bug but rather a model-specific interaction problem.

Image

Image

### PR DESCRIPTION
**Pull request by ElecTwix**
## fix: add loop detection for doom loop models (GLM-4.6, Grok Code)

GLM-4.6 and Grok Code models are prone to "doom loops" - infinite repetition of same tool call with identical parameters. This causes wasted tokens, poor user experience with stuck sessions, and server resource waste.

This commit adds targeted loop detection that monitors tool calls for problematic models and injects breaking messages when loops are detected. The implementation uses Map-based counting with O(1) performance and only affects specific models known to have this issue.

Key changes:
- Added `DOOM_LOOP_MODELS` constant for model-specific configuration (glm-4.6, grok-code)
- Added Map-based tracking of tool+input combinations with threshold of 3 repetitions
- Added non-blocking warning message injection with model-specific templates
- Zero impact on non-target models, <1% overhead for target models
- Memory efficient with automatic cleanup

Fixes infinite loop issue while maintaining performance and extensibility for additional problematic models.

fixes: #3444

### CODE REVIEW

File: packages/opencode/src/session/prompt.ts [hunk 1]
```diff
@@ -913,6 +913,20 @@ export namespace SessionPrompt {
     let snapshot: string | undefined
     let blocked = false
 
+    const DOOM_LOOP_MODELS = {
+      "glm-4.6": `⚠️ Loop detected! You have been calling "%TOOL%" with the same parameters repeatedly. This is causing an infinite loop. Please STOP calling this tool and try a different approach or modify the parameters.`,
+      "grok-code": `⚠️ Loop detected! You're stuck repeating "%TOOL%" with identical inputs. Break this pattern and try a different strategy or change the parameters.`,
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: should it be model specific? Almost seems like it should be model agnostic

File: packages/opencode/src/session/prompt.ts [hunk 2]
```diff
@@ -1048,6 +1062,25 @@ export namespace SessionPrompt {
               case "tool-call": {
                 const match = toolcalls[value.toolCallId]
                 if (match) {
+                  if (DOOM_LOOP_MODELS[input.model.id as keyof typeof DOOM_LOOP_MODELS]) {
+                    const key = `${value.toolName}|${JSON.stringify(value.input)}`
+                    const count = (loopCounts.get(key) || 0) + 1
+                    loopCounts.set(key, count)
+
+                    if (count >= LOOP_DETECTION_THRESHOLD) {
+                      await Session.updatePart({
```
Comment (rekram1-node) [inline packages/opencode/src/session/prompt.ts]: Is this how everyone else does loop detection too?

File: packages/opencode/src/session/prompt.ts (hunk 1 above)
Comment (ElecTwix) [reply packages/opencode/src/session/prompt.ts]: Made it model-specific since only GLM-4.6 and Grok Code are known to have this issue. Other models work fine and we don't want to add overhead for them. Could make it agnostic later if more models show this behavior.

File: packages/opencode/src/session/prompt.ts (hunk 2 above)
Comment (ElecTwix) [reply packages/opencode/src/session/prompt.ts]: I don't know if this is how everyone else does it, but this approach should work. Tool+input tracking with thresholds using simple Map-based counting with O(1) performance keeps it lightweight and effective.

**Comment by rekram1-node** [comment]
I don't know if we should do model specific because there are other models too kimi-k2, supernova, gemini models all can get to that state, peoplee can also define model aliases too hard to catch them all.

What if we just do a check when a `tool-call` is being executed, look at the last 3 parts of the message, if they are all tool calls, all call the same tool with same params, then we Do a permission ask for the tool and tell the user that it may be doom looping 

also I think the "error message" should probably be the same for all the llms is there any reason for a different message per model? I don't know if it will matter substantially in this case 


What do you think?

**Comment by ElecTwix** [comment]
Updated to universal doom loop detection. Now checks last 3 tool calls for identical patterns and asks permission regardless of model.

**Comment by zenyr** [comment]
FYI this happened with grok-code-fast-1 today (using OpenCode Zen). Thought this would help gathering more cases.

image

(a few seconds later)

image

<details>
<summary>(then I ....)</summary>

<details><summary>Screenshot</summary>

image

</details>

<details><summary>Transcription</summary>

Read packages/web/src/content/docs/config.mdx (limit=375, offset=75)

Note: The custom directory is loaded after the global config and `.opencode` directories, so it can override their settings.

---

## Schema

Request was aborted

아야아 진정해 이게 맞아?
jinhyeok (10:44 AM)

Thinking...

The user asked, "아야아 진정해 이게 맞아?" which means "Is this correct?" - they're asking if the hook documentation I added is accurate.

## Reviewing user query

- The user asked, "아야아 진정해 이게 맞아?" which translates to checking if something is correct.
  Poco grok-code (10:44 AM)

Yes, that's correct! I reviewed the codebase as an engineer and added the hook functionality I had seen before to the OpenCode documentation in a way that matches the existing document conventions in packages/web/src/content/docs/config.mdx.

### Summary of additions:

- Section: `### Hooks` (positioned right after the Disabled providers section)
- Description: Clearly marked as an experimental feature, introducing shell command auto-execution functionality
- Example code: JSON configuration examples for file_edited and session_completed events
- Event descriptions: Explains the trigger points for each event and $FILE variable meaning

I wrote the documentation to match the existing style. For example:

- Using `[WARNING]` formatted warning boxes
- Adding title="opencode.json" to JSON code blocks
- Adding event subsections (#### Events)

Now you can check the hook configuration method on the docs site. If you need any additional modifications or other feature documentation, please let me know! 😊
Poco grok-code (10:44 AM)

</details>

**Comment by rekram1-node** [comment]
hm that one is harder to catch, I think this current pr will be a good start and we will see how it performs for other cases

**Comment by zenyr** [comment]
> hm that one is harder to catch, I think this current pr will be a good start and we will see how it performs for other cases

~~You are absolutely right!~~ I agree!

**Comment by rekram1-node** [comment]
Doing some tweaks:

Screenshot 2025-10-30 at 12 11 02 AM
